"""The instruments this platform exposes, as data, each with the decision it informs.

Specification 19.13, on the voice loop but true of everything: *"Counters that are never
surfaced are not observability."* This module is the answer to that. Every instrument here
has a name, a description that becomes its ``# HELP``, its labels, and a ``decision`` --
one sentence naming what an operator does differently when the number moves. An instrument
that cannot be given that sentence does not belong in the catalogue, and
:class:`~platform_observability.metrics.InstrumentSpec` refuses to be constructed without
one.

The list is derived from what the platform actually does rather than from what is
conventional to measure: admissions and their denial codes, execution grants through their
lifecycle, the outbox and the worker that drains it, the provider, webhooks, reconciliation
and refunds. Each of those is a place where the system decides something or waits for
something, and those are the only two things worth counting.

The line this catalogue does not cross
--------------------------------------
None of these is a money record. ``commerce_refunds_open`` says how many refunds are
waiting; ``refunds`` and the hash chain in ``audit_events`` say what happened to each one.
``commerce_provider_requests_total`` says how Razorpay is behaving; ``provider_requests``
and the Money Action Proof Chain (spec 26.4) say what was sent and what came back. If a
question can only be answered from a metric, the answer is wrong -- the metric is sampled,
aggregated, capped and lost on restart, and every one of those is fine precisely because
nothing depends on it.

Adding your own
---------------
Do not edit this file to add instruments for another package. Define your own tuple of
specs beside the code that records them and register it::

    # packages/voice-runtime/src/voice_runtime/telemetry.py
    from platform_observability import InstrumentKind, InstrumentSpec

    VOICE_INSTRUMENTS = (
        InstrumentSpec(
            name="voice_frames_total",
            kind=InstrumentKind.COUNTER,
            description="Audio frames handled, by direction and disposition.",
            decision="Whether the queue is evicting under load (spec 19.13).",
            labels=("direction", "disposition"),
        ),
        ...
    )

    registry.register_all(VOICE_INSTRUMENTS)

Registration is idempotent for an identical spec and refuses a conflicting one, so two
packages can safely register the same shared catalogue and neither can silently redefine
the other's instrument.
"""

from __future__ import annotations

from typing import Final

from .metrics import AGE_BUCKETS, LATENCY_BUCKETS, InstrumentKind, InstrumentSpec, MetricsRegistry
from .timing import Timing

__all__ = [
    "ADMISSION_TIMING",
    "PLATFORM_INSTRUMENTS",
    "PROVIDER_TIMING",
    "WORKER_COMMAND_TIMING",
    "default_registry",
    "reset_default_registry",
]


def _counter(
    name: str, description: str, decision: str, labels: tuple[str, ...] = ()
) -> InstrumentSpec:
    return InstrumentSpec(
        name=name,
        kind=InstrumentKind.COUNTER,
        description=description,
        decision=decision,
        labels=labels,
    )


def _gauge(
    name: str, description: str, decision: str, labels: tuple[str, ...] = ()
) -> InstrumentSpec:
    return InstrumentSpec(
        name=name,
        kind=InstrumentKind.GAUGE,
        description=description,
        decision=decision,
        labels=labels,
    )


def _seconds(
    name: str,
    description: str,
    decision: str,
    labels: tuple[str, ...] = (),
    buckets: tuple[float, ...] = LATENCY_BUCKETS,
) -> InstrumentSpec:
    return InstrumentSpec(
        name=name,
        kind=InstrumentKind.HISTOGRAM,
        description=description,
        decision=decision,
        labels=labels,
        unit="seconds",
        buckets=buckets,
    )


# ------------------------------------------------------------------ the HTTP surface

_HTTP: Final[tuple[InstrumentSpec, ...]] = (
    _counter(
        "commerce_http_requests_total",
        "HTTP requests served, by route template, method and status class.",
        "The first question of any incident: is the API answering, and answering what. "
        "Split by status class so a rise in 4xx (a client integrating badly) is not read "
        "as a rise in 5xx (us).",
        ("route", "method", "status"),
    ),
    _seconds(
        "commerce_http_request_duration_seconds",
        "Wall time serving one HTTP request, by route template and method.",
        "Whether a slow checkout is the kernel, the database or the provider. Compare "
        "against commerce_admission_duration_seconds and the provider histogram: the "
        "difference between them is this service's own overhead.",
        ("route", "method"),
    ),
)
# ``route`` is the **template** (``/v1/checkouts/{checkout_id}``), never the resolved path.
# A resolved path puts a UUID in a label: unbounded cardinality, and -- worse -- a buyer's
# checkout id in an exported time series that outlives the request by weeks.


# ------------------------------------------------------- admission, the kernel's verdict

_ADMISSION: Final[tuple[InstrumentSpec, ...]] = (
    _counter(
        "commerce_admissions_total",
        "Kernel admission decisions, by operation and whether they were allowed.",
        "The allow rate is the platform's headline health number. A denial is the system "
        "working (ADR 0003 D15), so this counter is read together with the denial codes "
        "below rather than alarmed on by itself.",
        ("operation", "outcome"),
    ),
    _counter(
        "commerce_admission_denials_total",
        "Kernel denials by RecoveryCode, the deterministic reason the kernel refused.",
        "Which refusal dominates, which is a different question per code. Rising "
        "REAPPROVAL_REQUIRED means buyers are being asked to consent twice because prices "
        "or stock move under them; rising AUTHORITY_INSUFFICIENT means an agent is "
        "attempting what it may not; rising CONCURRENT_OPERATION means genuine contention "
        "and is expected under the two-tabs demonstration.",
        ("operation", "code"),
    ),
    _seconds(
        "commerce_admission_duration_seconds",
        "Time inside one kernel admission, lock acquisition included.",
        "Whether the single-winner locking is the latency floor. Admission holds "
        "checkout_versions FOR UPDATE, so its tail latency is what contention costs a "
        "buyer.",
        ("operation",),
    ),
    _counter(
        "commerce_safe_mode_blocks_total",
        "Operations refused because a platform operating mode was engaged.",
        "Whether the kill switch is currently costing buyers anything. Non-zero with "
        "commerce_safe_mode_engaged at 1 is the switch working; non-zero with the gauge at "
        "0 is a stale mode row and an incident.",
        ("operation", "mode"),
    ),
    _gauge(
        "commerce_safe_mode_engaged",
        "1 while a platform operating mode is restricting money actions, 0 otherwise.",
        "Whether the platform is refusing money actions right now. The first thing to "
        "check when submissions stop, and the difference between an outage and a decision.",
        ("scope", "mode"),
    ),
)


# --------------------------------------------------------------- execution grants

_GRANTS: Final[tuple[InstrumentSpec, ...]] = (
    _counter(
        "commerce_execution_grants_issued_total",
        "Execution Grants issued, by the operation they authorise.",
        "The denominator for every provider mutation: spec 25.6 requires every provider "
        "mutation to reference one consumed grant, so this is how many mutations were "
        "authorised.",
        ("operation",),
    ),
    _counter(
        "commerce_execution_grants_consumed_total",
        "Execution Grants consumed, by operation.",
        "Issued minus consumed is authority granted that never became a provider call. A "
        "persistent gap means the worker is not draining, or is crashing between consuming "
        "and sending.",
        ("operation",),
    ),
    _counter(
        "commerce_execution_grants_expired_total",
        "Execution Grants that reached their deadline unused and were expired by housekeeping.",
        "Whether authority is going stale before the worker gets to it. Every expiry is a "
        "buyer whose payment did not start; a rising rate is a capacity problem, not a "
        "cleanup statistic.",
        ("operation",),
    ),
    _counter(
        "commerce_execution_grants_revoked_total",
        "Execution Grants revoked before use, by the cause of revocation.",
        "Distinguishes deliberate withdrawal (a superseded checkout version) from "
        "abandonment. Revocation is correct behaviour; the label says which correctness.",
        ("operation", "cause"),
    ),
)


# ------------------------------------------------------------- the outbox and worker

_OUTBOX: Final[tuple[InstrumentSpec, ...]] = (
    _gauge(
        "commerce_outbox_depth",
        "Durable commands currently in each outbox status.",
        "Whether the worker is keeping up. PENDING climbing is backlog; LEASED climbing "
        "with PENDING flat is a worker that leases and then stalls; DEAD above zero is a "
        "command the platform has stopped retrying and needs a human.",
        ("status", "command_type"),
    ),
    _gauge(
        "commerce_outbox_oldest_pending_age_seconds",
        "Age of the oldest command still waiting to be leased.",
        "Depth hides one stuck row behind a healthy total. This does not: it is the "
        "latency a buyer is actually experiencing on the slowest work item.",
        ("command_type",),
    ),
    _counter(
        "commerce_worker_leases_total",
        "Commands leased by the worker, by command type.",
        "Throughput, and the denominator for the attempt outcomes below. Compared across "
        "worker ids it also shows whether SKIP LOCKED is spreading work evenly.",
        ("command_type",),
    ),
    _counter(
        "commerce_worker_attempts_total",
        "Worker command attempts by type and outcome (completed, failed, lease_lost).",
        "The retry rate. A high failed-to-completed ratio on one command type localises a "
        "fault to one handler; lease_lost is a redelivery race and is expected in small "
        "numbers.",
        ("command_type", "outcome"),
    ),
    _counter(
        "commerce_worker_dead_letters_total",
        "Commands buried after exhausting their attempts, by type and terminal code.",
        "Every increment is the platform announcing it has stopped trying, and each one "
        "owes a buyer an answer. This is the counter that pages someone; the evidence is "
        "the audited outbox.dead_letter event, never this number.",
        ("command_type", "code"),
    ),
    _seconds(
        "commerce_worker_command_duration_seconds",
        "Wall time running one leased command's handler, by type and outcome.",
        "Whether a backlog is caused by volume or by each command being slow. A handler "
        "slower than the lease deadline is the specific bug that produces duplicate "
        "provider calls.",
        ("command_type", "outcome"),
    ),
)


# ----------------------------------------------------------------- the provider

_PROVIDER: Final[tuple[InstrumentSpec, ...]] = (
    _counter(
        "commerce_provider_requests_total",
        "Requests to a payment provider, by operation and coarse outcome.",
        "Whether the provider is failing or we are sending it bad requests -- the outcome "
        "label separates the two, and they have opposite remedies. A rise in 'timeout' is "
        "the one that matters most: it means outcomes are unknown, not failed.",
        ("provider", "operation", "outcome"),
    ),
    _seconds(
        "commerce_provider_request_duration_seconds",
        "Wall time of one provider HTTP round trip, by operation and outcome.",
        "Where the timeout budget should sit. A p99 approaching the configured timeout "
        "means the platform is about to start manufacturing unknown payment states. Split "
        "by outcome because a failure is usually fast, and mixing failures into the "
        "histogram flatters the percentile that matters.",
        ("provider", "operation", "outcome"),
    ),
    _counter(
        "commerce_provider_retries_total",
        "Provider calls retried, by operation and the reason the first attempt did not settle.",
        "Whether idempotency is doing its job. Retries are safe here because every provider "
        "mutation carries a consumed grant, so this is a cost signal rather than a "
        "correctness one.",
        ("provider", "operation", "reason"),
    ),
)


# ------------------------------------------------------------------- webhooks

_WEBHOOKS: Final[tuple[InstrumentSpec, ...]] = (
    _counter(
        "commerce_webhook_deliveries_total",
        (
            "Webhook deliveries received, by event type and disposition: accepted, "
            "duplicate, or one of the rejection reasons."
        ),
        "Duplicates are read here as disposition='duplicate' rather than on a counter of "
        "their own, so accepted and duplicate always sum to what the provider sent. A rise "
        "in rejected_signature is a rotated secret or somebody probing; a rise in "
        "duplicate is the provider retrying, which is the dedupe working (ADR 0003 D7).",
        ("event_type", "disposition"),
    ),
    _seconds(
        "commerce_webhook_apply_lag_seconds",
        "Time from accepting a webhook to the worker applying its state change.",
        "How stale the buyer's view of their own payment is. The receiver answers 200 "
        "before the state moves by design, so this is the only measure of that gap.",
        ("event_type",),
        AGE_BUCKETS,
    ),
)


# ------------------------------------------------------- reconciliation and refunds

_RECONCILIATION: Final[tuple[InstrumentSpec, ...]] = (
    _counter(
        "commerce_reconciliation_runs_total",
        "Reconciliation attempts, by what was reconciled and how the run concluded.",
        "Whether unknown states are being resolved or merely re-queued. A run concluding "
        "'still_unknown' repeatedly on the same subject is what escalation exists for.",
        ("kind", "conclusion"),
    ),
    _counter(
        "commerce_reconciliation_findings_total",
        "Discrepancies found between our recorded state and the provider's.",
        "Every finding is money whose state we had wrong until now. This number should be "
        "near zero in steady state; any sustained level means an evidence path is missing "
        "an update, not that reconciliation is working hard.",
        ("kind", "finding"),
    ),
    _gauge(
        "commerce_payments_unresolved",
        "Payment attempts sitting in a non-terminal state that needs provider evidence.",
        "The size of the set of buyers who do not yet know whether they paid. It should "
        "drain; a floor that does not is the reconciliation loop failing quietly.",
        ("state",),
    ),
)

_REFUNDS: Final[tuple[InstrumentSpec, ...]] = (
    _counter(
        "commerce_refund_requests_total",
        "Refund requests reaching the kernel, by whether they were admitted and why not.",
        "Whether the refund policy is refusing buyers who expect a refund. Read with the "
        "denial codes: REFUND_REVIEW_REQUIRED is a human queue forming, not a rejection.",
        ("outcome", "code"),
    ),
    _gauge(
        "commerce_refunds_open",
        "Refunds currently in each non-terminal wire state.",
        "ESCALATED above zero means a human owes a buyer an answer. UNKNOWN above zero "
        "means the platform does not know whether a buyer's money moved -- the single most "
        "important operational number in this system. Neither is the refund record: that is "
        "the row in `refunds` and its audit chain.",
        ("wire_state",),
    ),
    _counter(
        "commerce_refund_escalations_total",
        "Refunds escalated to human review, by the reason the automatic path gave up.",
        "The rate at which automation hands work to people. Each one has a support case "
        "behind it; this counter sizes the queue, and the case carries the evidence.",
        ("reason",),
    ),
)


# ---------------------------------------------------------------------- audit

_AUDIT: Final[tuple[InstrumentSpec, ...]] = (
    _counter(
        "commerce_audit_appends_total",
        "Audit events appended, by aggregate type.",
        "The operational view of the evidential system: whether evidence is still being "
        "written at the rate the traffic implies. A stall here with traffic flowing is a "
        "reason to look at the audit stream itself, which is where the truth is.",
        ("aggregate_type",),
    ),
    _counter(
        "commerce_audit_append_conflicts_total",
        "Audit appends that lost a sequence race and raised AuditConcurrencyError.",
        "The advisory lock in transaction_kernel.audit should make these vanishingly rare. "
        "A sustained rate means two writers are contending on one aggregate stream and "
        "somebody's state change is being rolled back with it.",
        ("aggregate_type",),
    ),
    _counter(
        "commerce_audit_chain_verifications_total",
        "Chain verifications run, by verdict (intact, or the BreakKind that was found).",
        "A verdict other than 'intact' is an integrity incident and is the one signal here "
        "that should wake somebody at night. The verification itself, not this counter, is "
        "the evidence.",
        ("verdict",),
    ),
)


#: Everything above, in one tuple, ready for
#: :meth:`~platform_observability.metrics.MetricsRegistry.register_all`.
PLATFORM_INSTRUMENTS: Final[tuple[InstrumentSpec, ...]] = (
    *_HTTP,
    *_ADMISSION,
    *_GRANTS,
    *_OUTBOX,
    *_PROVIDER,
    *_WEBHOOKS,
    *_RECONCILIATION,
    *_REFUNDS,
    *_AUDIT,
)


# ------------------------------------------------------------------- timings

# There is deliberately no HTTP ``Timing``. A ``timed`` block captures its metrics handle
# when it opens, and an HTTP request's tenant is not known until a dependency has resolved
# the bearer token part-way through -- so a Timing would label every request with no tenant
# and drop it. The API middleware measures with ``time.perf_counter`` and records both HTTP
# instruments after dispatch, when the tenant is known. See docs/adr/0007-observability.md.

#: One kernel admission. No outcome counter: an admission's verdict is a decision with a
#: reason code, and ``commerce_admission_denials_total`` carries it with more fidelity than
#: an ok/error label could.
ADMISSION_TIMING: Final[Timing] = Timing(duration="commerce_admission_duration_seconds")

#: One provider round trip. The outcome counter is the requests counter, so a call is
#: counted exactly once and its latency and its verdict cannot disagree. Both instruments
#: declare ``outcome``, which is what a Timing with an outcome counter requires.
PROVIDER_TIMING: Final[Timing] = Timing(
    duration="commerce_provider_request_duration_seconds",
    outcome_counter="commerce_provider_requests_total",
)

#: One leased command's handler. Duration and outcome share the ``outcome`` label, so the
#: histogram can be read for successes alone -- failures are usually fast and would
#: otherwise flatter the average.
WORKER_COMMAND_TIMING: Final[Timing] = Timing(
    duration="commerce_worker_command_duration_seconds",
    outcome_counter="commerce_worker_attempts_total",
)


# ------------------------------------------------------------ the default registry

_DEFAULT: MetricsRegistry | None = None


def default_registry() -> MetricsRegistry:
    """The process-wide registry, with :data:`PLATFORM_INSTRUMENTS` already registered.

    Three packages record into one exposition and none of them should have to be handed a
    registry object through its constructor to do it, so there is a singleton. It is
    created on first use rather than at import, because a module that builds state at
    import time is a module that cannot be tested twice in one process.

    A component that wants its own -- a test, or a second exposition on a different
    endpoint -- constructs :class:`~platform_observability.metrics.MetricsRegistry`
    directly. Nothing here requires the singleton.
    """
    global _DEFAULT
    if _DEFAULT is None:
        registry = MetricsRegistry()
        registry.register_all(PLATFORM_INSTRUMENTS)
        _DEFAULT = registry
    return _DEFAULT


def reset_default_registry() -> None:
    """Drop the process-wide registry. For tests, and for nothing else.

    Named plainly rather than hidden behind an underscore: a test that needs a clean
    registry should not have to reach into a private, and a production call site that
    reaches for this is easy to spot in review.
    """
    global _DEFAULT
    _DEFAULT = None
