"""Registry A capabilities, the broker that derives principals and gates calls, and the
tool factory that is the only source of a specialist's tools.

The provenance gates the factory calls live in ``core/provenance.py``; they are
re-exported here so a caller that holds a toolset can name the same gate the tool will.
"""

from ..core.provenance import (
    MAX_BASKET_LINES,
    MAX_LINE_QUANTITY,
    PROVENANCE_CAP,
    PROVENANCE_STATE_KEY,
    Held,
    SessionProvenance,
    check_checkout_provenance,
    check_line_count,
    check_order_provenance,
    check_quantity,
    check_sku_provenance,
    session_write_lock,
)
from .broker import (
    REASON_CAPABILITY_MISSING,
    REASON_TOOL_BUDGET_EXHAUSTED,
    REASON_TOOL_FAILED,
    REASON_TOOL_NOT_BOUND,
    REASON_TOOL_NOT_REGISTERED,
    REASON_TOOL_UNAVAILABLE,
    ToolContextLike,
    ToolErrorGate,
    ToolGate,
    ToolLike,
    derive_principal,
    make_capability_gate,
    make_tool_error_gate,
)
from .registry import (
    AGENT_ALLOWLIST,
    ALL_CAPABILITIES,
    KERNEL_INTERNAL_OPERATIONS,
    PRESENTATION_TOOLS,
    REGISTRY_A,
    SPECIALIST_TOOLS,
    TRUSTED_OPERATOR_ACTIONS,
    TRUSTED_SURFACE_ACTIONS,
    WRITE_TOOLS,
    AgentRole,
    Capability,
    capability_for,
    tools_for_role,
)
from .tools import (
    IDENTITY_PARAMETER_NAMES,
    STATE_BASKET_ID,
    STATE_CHECKOUT_HASH,
    STATE_CHECKOUT_ID,
    STATE_CHECKOUT_VERSION,
    BindingLike,
    BoundTool,
    BoundToolset,
    FactoryContext,
    ToolBuilder,
    ToolFunc,
    build_tools,
    build_toolset,
)

__all__ = [
    "AGENT_ALLOWLIST",
    "ALL_CAPABILITIES",
    "IDENTITY_PARAMETER_NAMES",
    "KERNEL_INTERNAL_OPERATIONS",
    "MAX_BASKET_LINES",
    "MAX_LINE_QUANTITY",
    "PRESENTATION_TOOLS",
    "PROVENANCE_CAP",
    "REASON_CAPABILITY_MISSING",
    "REASON_TOOL_BUDGET_EXHAUSTED",
    "REASON_TOOL_FAILED",
    "REASON_TOOL_NOT_BOUND",
    "REASON_TOOL_NOT_REGISTERED",
    "REASON_TOOL_UNAVAILABLE",
    "REGISTRY_A",
    "SPECIALIST_TOOLS",
    "STATE_BASKET_ID",
    "STATE_CHECKOUT_HASH",
    "STATE_CHECKOUT_ID",
    "STATE_CHECKOUT_VERSION",
    "PROVENANCE_STATE_KEY",
    "TRUSTED_OPERATOR_ACTIONS",
    "TRUSTED_SURFACE_ACTIONS",
    "WRITE_TOOLS",
    "AgentRole",
    "BindingLike",
    "BoundTool",
    "BoundToolset",
    "Capability",
    "FactoryContext",
    "Held",
    "SessionProvenance",
    "ToolBuilder",
    "ToolContextLike",
    "ToolErrorGate",
    "ToolFunc",
    "ToolGate",
    "ToolLike",
    "build_tools",
    "build_toolset",
    "capability_for",
    "check_checkout_provenance",
    "check_line_count",
    "check_order_provenance",
    "check_quantity",
    "check_sku_provenance",
    "derive_principal",
    "make_capability_gate",
    "make_tool_error_gate",
    "session_write_lock",
    "tools_for_role",
]
