import type {
  AuditStreamVerificationOut,
  InspectorAttemptOut,
  OrderOut,
  OutboxOut,
  ProofChainOut,
  RefundItem,
  RetainedRevenueOut,
  ReviewQueueCase,
  SafeModeOut,
  SpecRevenueMetric,
} from "./types";

export const DEMO_RETAINED_REVENUE_HEADLINE: RetainedRevenueOut = {
  checkout_id: "chk_hero_stale_refusal_01",
  merchant_id: "demo-grocery",
  currency: "INR",
  stale_version: 1,
  stale_approved_minor: 57995,
  stale_invalidated_at: "2026-09-04T23:59:00Z",
  corrected_version: 2,
  corrected_total_minor: 68195,
  captured_minor: 68195,
  captured_from: "PROVIDER_FETCH",
  difference_minor: 10200,
  direction: "RETAINED_GAIN",
  refunded_minor: 0,
  net_retained_minor: 10200,
  controlled_scenario: true,
  explanation:
    "Version 1 at ₹579.95 was refused by the kernel because pricing changed underneath in-flight checkout. Version 2 at ₹681.95 was re-approved by the buyer on the trusted surface and captured. The ₹102.00 difference is margin preserved by refusing stale consent.",
  is_live: false,
};

export interface ScenarioBreakdownItem {
  scenarioId: string;
  checkoutId: string;
  timestamp: string;
  buyerSession: string;
  sku: string;
  productName: string;
  approvedMinor: number;
  liveMinor: number;
  buyerPaidMinor: number;
  preservedDeltaMinor: number;
  hashV1: string;
  hashV2: string;
  reason: string;
}

export const DEMO_RETAINED_SCENARIOS: ScenarioBreakdownItem[] = [
  {
    scenarioId: "scen_milk_surge_01",
    checkoutId: "chk_refusal_8842",
    timestamp: "2026-09-05 01:14:22 UTC",
    buyerSession: "sess_buyer_9921",
    sku: "GRO-DAIRY-001",
    productName: "Amul Taaza Toned Milk (500 ml)",
    approvedMinor: 10825,
    liveMinor: 15185,
    buyerPaidMinor: 15185,
    preservedDeltaMinor: 4360,
    hashV1: "a4f1028e4419cb772093bf11",
    hashV2: "e3b0c44298fc1c149afbf4c8",
    reason: "Merchant applied ₹10.00 price surge + delivery slab adjustment during proposal.",
  },
  {
    scenarioId: "scen_oil_surge_02",
    checkoutId: "chk_refusal_8814",
    timestamp: "2026-09-04 23:35:04 UTC",
    buyerSession: "sess_buyer_6619",
    sku: "GRO-STPL-004",
    productName: "Fortune Kachi Ghani Mustard Oil 1 L",
    approvedMinor: 21735,
    liveMinor: 28885,
    buyerPaidMinor: 28885,
    preservedDeltaMinor: 7150,
    hashV1: "88cf112a99182310ff77e199",
    hashV2: "1198acdf8820391100aa3241",
    reason: "Commodity spot market price adjustment revalidated prior to payment capture.",
  },
  {
    scenarioId: "scen_rice_surge_03",
    checkoutId: "chk_refusal_8790",
    timestamp: "2026-09-04 22:50:29 UTC",
    buyerSession: "sess_buyer_3301",
    sku: "GRO-STPL-001",
    productName: "India Gate Classic Basmati Rice 5 kg",
    approvedMinor: 52395,
    liveMinor: 57645,
    buyerPaidMinor: 57645,
    preservedDeltaMinor: 5250,
    hashV1: "55bb3901ca88710299cc1245",
    hashV2: "99aa8710ee9928190022ef77",
    reason: "Tax rate adjustment from GST reclassification caught by canonical hasher.",
  },
  {
    scenarioId: "scen_noodle_surge_04",
    checkoutId: "chk_refusal_8741",
    timestamp: "2026-09-04 21:12:10 UTC",
    buyerSession: "sess_buyer_1194",
    sku: "GRO-SNCK-001",
    productName: "Maggi 2-Minute Masala Noodles (Pack of 4)",
    approvedMinor: 13252,
    liveMinor: 15044,
    buyerPaidMinor: 15044,
    preservedDeltaMinor: 1792,
    hashV1: "447192a01188392077bb1109",
    hashV2: "3381900bfa77281922990021",
    reason: "Batch replenishment price update enacted while checkout was in session.",
  },
];

export const DEMO_PREVENTED_EVENTS = [
  {
    id: "prev_dup_01",
    type: "DUPLICATE_CHARGE_PREVENTED",
    checkoutId: "chk_dup_4921",
    title: "Double-Submit Concurrency Lock",
    description: "Two browser tabs fired simultaneous submit on version 2. Single-winner lock admitted attempt 1 and refused attempt 2 with DUPLICATE_OPERATION.",
    amountMinor: 68195,
    preventedLossMinor: 68195,
    timestamp: "2026-09-05 00:45:10 UTC",
    proofChainRef: "/inspector/payment-attempts/att_dup_winner_01",
  },
  {
    id: "prev_ref_01",
    type: "DOUBLE_REFUND_PREVENTED",
    checkoutId: "chk_ref_9912",
    title: "In-Flight Refund Idempotency",
    description: "Second refund API call triggered while provider settlement was in REFUND_PENDING. Kernel refused with REFUND_ALREADY_IN_FLIGHT.",
    amountMinor: 35000,
    preventedLossMinor: 35000,
    timestamp: "2026-09-04 22:15:33 UTC",
    proofChainRef: "/inspector/payment-attempts/att_ref_idemp_02",
  },
  {
    id: "prev_stale_01",
    type: "STALE_APPROVAL_REFUSED",
    checkoutId: "chk_refusal_8842",
    title: "Stale Version 1 Payment Blocked",
    description: "Buyer agent presented Version 1 authorization after merchant price injection. Transaction Assurance Kernel refused admission with STALE_APPROVAL_REFUSED.",
    amountMinor: 10825,
    preventedLossMinor: 4360,
    timestamp: "2026-09-05 01:14:22 UTC",
    proofChainRef: "/checkouts/chk_refusal_8842/proof",
  },
];

export const DEMO_SPEC_9_3_METRICS: SpecRevenueMetric[] = [
  {
    key: "attempted_revenue",
    label: "Attempted Revenue",
    valueDisplay: "₹8,45,210.00",
    description: "Total gross amount across all buyer checkout proposals created by agents.",
    source: "simulated",
  },
  {
    key: "admitted_revenue",
    label: "Admitted Revenue",
    valueDisplay: "₹7,92,400.00",
    description: "Checkouts admitted by kernel after validating version hash & single-use grant.",
    source: "simulated",
  },
  {
    key: "authorized_revenue",
    label: "Authorized Revenue",
    valueDisplay: "₹7,65,100.00",
    description: "Payments authorized on trusted surface with explicit buyer consent.",
    source: "simulated",
  },
  {
    key: "captured_revenue",
    label: "Captured Revenue",
    valueDisplay: "₹7,42,850.00",
    description: "Settled payments verified strictly via WEBHOOK or PROVIDER_FETCH.",
    source: "simulated",
  },
  {
    key: "refunded_revenue",
    label: "Refunded Revenue",
    valueDisplay: "₹18,400.00",
    description: "Settled refunds executed under fresh single-use REFUND_EXECUTE grants.",
    source: "simulated",
  },
  {
    key: "net_retained_revenue",
    label: "Net Retained Revenue",
    valueDisplay: "₹7,24,450.00",
    description: "Captured revenue less refunds, returns, and merchant discount cost.",
    source: "simulated",
  },
  {
    key: "payment_completion_rate",
    label: "Payment Completion Rate",
    valueDisplay: "97.1%",
    description: "Ratio of admitted execution grants to final verified captures.",
    source: "simulated",
  },
  {
    key: "refund_rate",
    label: "Refund Rate",
    valueDisplay: "2.4%",
    description: "Refunded gross minor volume relative to total captured revenue.",
    source: "simulated",
  },
  {
    key: "cancellation_rate",
    label: "Cancellation Rate",
    valueDisplay: "1.8%",
    description: "Proposals cancelled or expired before payment authorization.",
    source: "simulated",
  },
  {
    key: "average_order_value",
    label: "Average Order Value (AOV)",
    valueDisplay: "₹684.20",
    description: "Mean captured basket value across confirmed merchant sales.",
    source: "simulated",
  },
  {
    key: "conversion_after_reapproval",
    label: "Price Re-Approval Conversion",
    valueDisplay: "92.4%",
    description: "Buyers who authorized Version 2 after price-surge refusal.",
    source: "simulated",
  },
  {
    key: "stale_refusals_count",
    label: "Stale Approvals Refused",
    valueDisplay: "34 checkouts",
    description: "In-flight proposals safely stopped to prevent uncollected merchant surge.",
    source: "simulated",
  },
  {
    key: "invariant_violations",
    label: "Kernel Invariant Violations",
    valueDisplay: "0 (100% Protected)",
    description: "Zero multi-grant provider calls; zero browser callback captures.",
    source: "simulated",
  },
  {
    key: "uncollected_surge_prevented",
    label: "Uncollected Surge Preserved",
    valueDisplay: "₹18,552.00",
    description: "Cumulative margin retained by refusing out-of-date basket proposals.",
    source: "simulated",
  },
];

export const DEMO_OUTBOX: OutboxOut = {
  commands: [
    {
      command_id: "cmd_reconcile_9901",
      command_type: "RECONCILE_PAYMENT",
      status: "PENDING",
      attempts: 0,
      available_at: "2026-09-05T01:30:00Z",
      leased_until: null,
      correlation_id: "corr_rec_9901",
      created_at: "2026-09-05T01:29:55Z",
    },
    {
      command_id: "cmd_fetch_capture_8812",
      command_type: "PROVIDER_FETCH",
      status: "DONE",
      attempts: 1,
      available_at: "2026-09-05T01:28:10Z",
      leased_until: null,
      correlation_id: "corr_fet_8812",
      created_at: "2026-09-05T01:28:09Z",
    },
    {
      command_id: "cmd_release_res_8799",
      command_type: "INVENTORY_RELEASE",
      status: "DONE",
      attempts: 1,
      available_at: "2026-09-05T01:20:00Z",
      leased_until: null,
      correlation_id: "corr_rel_8799",
      created_at: "2026-09-05T01:19:59Z",
    },
    {
      command_id: "cmd_dead_reconcile_09",
      command_type: "RECONCILE_PAYMENT",
      status: "DEAD",
      attempts: 6,
      available_at: "2026-09-05T01:05:00Z",
      leased_until: null,
      correlation_id: "corr_dead_09",
      created_at: "2026-09-05T01:00:00Z",
      last_error: "Provider endpoint 504 Gateway Timeout exhausted 6 exponential backoff retries (ADR D13)",
    },
  ],
  counts: {
    PENDING: 1,
    LEASED: 0,
    DONE: 142,
    FAILED: 0,
    DEAD: 1,
  },
  limit: 50,
  is_live: false,
};

export const DEMO_SAFE_MODE: SafeModeOut = {
  mode: "NORMAL",
  scope: "TENANT",
  tenant_id: "demo-grocery",
  safe_mode: false,
  reason_code: "SYSTEM_HEALTHY",
  actor: "system",
  since: null,
  banner: null,
  blocked: ["DISPATCH_NEW_GRANTS", "ADMIT_NON_ESSENTIAL"],
  still_available: ["REFUND_PROCESSING", "INSPECTION_READS", "OUTBOX_DRAIN"],
  permitted: {
    "checkout.admit": true,
    "payment.capture": true,
    "refund.request": true,
  },
  revoked_grant_ids: [],
  is_live: false,
};

export const DEMO_ORDERS: OrderOut[] = [
  {
    order_id: "ord_demo_1001",
    checkout_id: "chk_hero_stale_refusal_01",
    status: "CAPTURED",
    total_minor: 68195,
    currency: "INR",
    checkout_version: 2,
    capture_evidence_source: "PROVIDER_FETCH",
    created_at: "2026-09-05T01:15:30Z",
    refunds: [],
  },
  {
    order_id: "ord_demo_1002",
    checkout_id: "chk_std_order_02",
    status: "CAPTURED",
    total_minor: 52000,
    currency: "INR",
    checkout_version: 1,
    capture_evidence_source: "WEBHOOK",
    created_at: "2026-09-05T00:55:12Z",
    refunds: [],
  },
  {
    order_id: "ord_demo_1003",
    checkout_id: "chk_ref_order_03",
    status: "PARTIALLY_REFUNDED",
    total_minor: 48000,
    currency: "INR",
    checkout_version: 1,
    capture_evidence_source: "PROVIDER_FETCH",
    created_at: "2026-09-04T22:40:00Z",
    refunds: [
      {
        refund_id: "ref_1003_a",
        status: "PROCESSED",
        amount_minor: 12000,
        reason: "Customer returned damaged dairy carton",
      },
    ],
  },
  {
    order_id: "ord_demo_1004",
    checkout_id: "chk_pending_order_04",
    status: "PENDING_APPROVAL",
    total_minor: 31500,
    currency: "INR",
    checkout_version: 1,
    capture_evidence_source: "NONE",
    created_at: "2026-09-05T01:32:00Z",
    refunds: [],
  },
];

export const DEMO_REFUNDS: RefundItem[] = [
  {
    refund_id: "ref_pending_901",
    order_id: "ord_demo_1003",
    checkout_id: "chk_ref_order_03",
    amount_minor: 12000,
    currency: "INR",
    state: "REFUND_PENDING",
    provider_refund_id: null,
    reason: "Customer reported damaged dairy carton",
    reconciliation_attempts: 1,
    created_at: "2026-09-05T01:10:00Z",
  },
  {
    refund_id: "ref_unknown_902",
    order_id: "ord_demo_1005",
    checkout_id: "chk_order_05",
    amount_minor: 25000,
    currency: "INR",
    state: "REFUND_UNKNOWN",
    provider_refund_id: "rfnd_rzp_mock_9921",
    reason: "Item out of stock during picking",
    reconciliation_attempts: 3,
    created_at: "2026-09-05T00:40:00Z",
  },
  {
    refund_id: "ref_failed_903",
    order_id: "ord_demo_1006",
    checkout_id: "chk_order_06",
    amount_minor: 8500,
    currency: "INR",
    state: "REFUND_FAILED",
    provider_refund_id: null,
    reason: "Beneficiary bank account closed",
    reconciliation_attempts: 6,
    created_at: "2026-09-04T23:15:00Z",
  },
  {
    refund_id: "ref_settled_904",
    order_id: "ord_demo_1007",
    checkout_id: "chk_order_07",
    amount_minor: 15000,
    currency: "INR",
    state: "PROCESSED",
    provider_refund_id: "rfnd_rzp_settled_441",
    reason: "Promotional credit adjustment",
    reconciliation_attempts: 1,
    created_at: "2026-09-04T21:00:00Z",
  },
];

export const DEMO_REVIEW_QUEUE: ReviewQueueCase[] = [
  {
    case_id: "case_rev_001",
    checkout_id: "chk_refusal_8842",
    order_id: null,
    blocking_reason_code: "PRICE_SURGE_SUSPECTED",
    escalated_at: "2026-09-05T01:14:22Z",
    provider_state_at_escalation: "NO_ATTEMPT",
    proof_chain_ref: "/checkouts/chk_refusal_8842/proof",
    redacted_timeline_snippet: "v1 proposal invalidated due to merchant catalogue price jump. v2 awaiting human re-approval.",
    amount_minor: 15185,
    currency: "INR",
  },
  {
    case_id: "case_rev_002",
    checkout_id: "chk_esc_reconcile_02",
    order_id: "ord_esc_02",
    blocking_reason_code: "PROVIDER_UNREACHABLE_ESCALATED",
    escalated_at: "2026-09-05T01:05:00Z",
    provider_state_at_escalation: "ATTEMPT_SUBMITTED",
    proof_chain_ref: "/inspector/payment-attempts/att_esc_02",
    redacted_timeline_snippet: "Reconciliation worker exhausted 6 backoff cycles without authoritative provider confirmation.",
    amount_minor: 52000,
    currency: "INR",
  },
];

export const DEMO_PROOF_CHAIN: ProofChainOut = {
  checkout_id: "chk_hero_stale_refusal_01",
  tenant_id: "demo-grocery",
  merchant_id: "demo-grocery",
  payment_attempt_id: "att_hero_02",
  attempt_ids: ["att_hero_01", "att_hero_02"],
  links: {
    "1_intent": { buyer_ref: "buyer-sess-01", intent: "GROCERY_CHECKOUT" },
    "2_merchant_state": { catalogue_rev: 12, price_hash: "a4f1028e..." },
    "3_checkout": { version: 2, total_minor: 68195 },
    "4_policy_receipt": { receipt_id: "rec_pol_02", hash: "99aa8710..." },
    "5_approval": { approved_by: "human_buyer", version: 2 },
    "6_decision": { outcome: "ADMITTED", grant_issued: true },
    "7_grant": { grant_id: "grnt_exec_02", single_use: true },
    "8_provider_evidence": { source: "PROVIDER_FETCH", razorpay_payment_id: "pay_MOCK123" },
    "9_capture": { captured_minor: 68195, confirmed_at: "2026-09-05T01:15:30Z" },
    "10_final_state": { status: "CAPTURED", refunds_count: 0 },
  },
  verdict: {
    tier: "VERIFIED_TRUSTED",
    ok: true,
    checks: [
      { name: "version_pinned_approval", ok: true, applicable: true, detail: "v2 approved matches v2 admitted" },
      { name: "single_use_execution_grant", ok: true, applicable: true, detail: "1 grant issued, 1 consumed" },
      { name: "verified_capture_source", ok: true, applicable: true, detail: "Source is PROVIDER_FETCH, not BROWSER_CALLBACK" },
      { name: "hash_chain_intact", ok: true, applicable: true, detail: "Audit sequence continuous with 0 breaks" },
    ],
    failed: [],
  },
  audit_streams: {
    checkout: "stream_chk_hero_01",
    payment_attempt: "stream_att_hero_02",
  },
  is_live: false,
};

export const DEMO_AUDIT_VERIFICATION: AuditStreamVerificationOut = {
  stream_id: "stream_chk_hero_01",
  aggregate_type: "checkout",
  aggregate_id: "chk_hero_stale_refusal_01",
  intact: true,
  chain_length: 14,
  head_sequence: 14,
  first_broken_sequence: null,
  verified_at: "2026-09-05T01:35:00Z",
  is_live: false,
};

export const DEMO_INSPECTOR: InspectorAttemptOut = {
  payment_attempt_id: "att_hero_02",
  checkout_id: "chk_hero_stale_refusal_01",
  checkout_version: 2,
  status: "CAPTURED",
  amount_minor: 68195,
  currency: "INR",
  provider_payment_id: "pay_rzp_mock_hero_02",
  provider_order_id: "order_rzp_mock_hero_02",
  timeline: [
    { seq: 1, event_type: "CHECKOUT_PROPOSED_V1", occurred_at: "2026-09-05T01:12:00Z", details: "Initial total ₹579.95" },
    { seq: 2, event_type: "SCENARIO_INJECTION", occurred_at: "2026-09-05T01:13:00Z", details: "Amul Taaza surged ₹28.00 ➔ ₹38.00" },
    { seq: 3, event_type: "STALE_APPROVAL_REFUSED", occurred_at: "2026-09-05T01:14:00Z", details: "v1 invalidated due to hash mismatch" },
    { seq: 4, event_type: "CHECKOUT_PROPOSED_V2", occurred_at: "2026-09-05T01:14:30Z", details: "Corrected total ₹681.95" },
    { seq: 5, event_type: "BUYER_APPROVED_V2", occurred_at: "2026-09-05T01:15:00Z", details: "Approved on trusted surface" },
    { seq: 6, event_type: "EXECUTION_GRANT_ISSUED", occurred_at: "2026-09-05T01:15:02Z", details: "Single-use grant grnt_exec_02" },
    { seq: 7, event_type: "CAPTURED_BY_PROVIDER_FETCH", occurred_at: "2026-09-05T01:15:30Z", details: "Verified capture ₹681.95" },
  ],
  grants: [
    { grant_id: "grnt_exec_02", grant_type: "PAYMENT_CAPTURE", status: "CONSUMED", expires_at: "2026-09-05T01:45:00Z", consumed_at: "2026-09-05T01:15:30Z" },
  ],
  outbox_commands: [
    {
      command_id: "cmd_fetch_02",
      command_type: "PROVIDER_FETCH",
      status: "DONE",
      attempts: 1,
      available_at: "2026-09-05T01:15:05Z",
      leased_until: null,
      correlation_id: "corr_02",
      created_at: "2026-09-05T01:15:03Z",
    },
  ],
  provider_requests: [
    {
      provider_request_id: "req_rzp_01",
      operation: "PAYMENTS_FETCH",
      method: "GET",
      url: "https://api.razorpay.com/v1/payments/pay_rzp_mock_hero_02",
      http_status: 200,
      outcome_code: "SUCCESS",
      request_at: "2026-09-05T01:15:28Z",
    },
  ],
  webhook_deliveries: [
    {
      inbox_id: "inbox_rzp_01",
      event_type: "payment.captured",
      signature_verified: true,
      duplicate: false,
      duplicate_count: 0,
      received_at: "2026-09-05T01:15:29Z",
    },
  ],
  reconciliation_runs: [],
  order: {
    order_id: "ord_demo_1001",
    state: "CAPTURED",
    amount_minor: 68195,
    currency: "INR",
    capture_evidence: { source: "PROVIDER_FETCH", verified_at: "2026-09-05T01:15:30Z" },
    created_at: "2026-09-05T01:15:30Z",
  },
  refunds: [],
  findings: [
    { name: "one_grant_per_provider_mutation", ok: true, detail: "1 provider mutation, 1 consumed grant, 0 ungranted, 0 reused" },
    { name: "no_unconsumed_grant_left_live", ok: true, detail: "grnt_exec_02=CONSUMED" },
    { name: "capture_came_from_a_verified_channel", ok: true, detail: "order confirmed from 'PROVIDER_FETCH'" },
    { name: "every_applied_webhook_was_signature_verified", ok: true, detail: "1 delivery, 0 applied unverified" },
    { name: "redeliveries_changed_nothing", ok: true, detail: "0 redelivered event(s)" },
    { name: "refunds_within_capture", ok: true, detail: "0 refunded of 68195 INR" },
  ],
  is_live: false,
};
