/**
 * Which local image files exist for a SKU, and which photograph stands for a category.
 *
 * Every picture this storefront shows was downloaded into `public/` and is served from
 * this origin. The Content-Security-Policy in `src/lib/security/csp.ts` names no external
 * image host, so a hotlinked URL does not render at all -- which is the point. A grocery
 * page whose photographs come from someone else's CDN both breaks the day that CDN moves
 * a path and tells that third party which products a buyer paused on.
 *
 * The table below is a literal inventory of what is on disk, generated by listing
 * `public/products`. It records a count rather than a list of filenames because the
 * naming is regular: the first shot is `<SKU>.webp` and the rest are `<SKU>_2.webp`
 * upward with no gaps. Keeping it as data means a SKU with no photograph is a fact this
 * module knows, not a broken <img> the buyer discovers.
 */

/** SKU to the number of `.webp` files present for it. Generated from `public/products`. */
const VARIANT_COUNTS: Readonly<Record<string, number>> = {
  // bakery
  "BAKE-BAKE-013": 1, "BRIT-BAKE-001": 1, "BRIT-BAKE-003": 1, "BRIT-BAKE-006": 1,
  "BRIT-BAKE-007": 1, "ENGL-BAKE-002": 1, "ENGL-BAKE-004": 1, "ENGL-BAKE-005": 1,
  "ENGL-BAKE-009": 1, "ENGL-BAKE-010": 1, "ENGL-BAKE-012": 1, "HEAL-BAKE-008": 1,
  "WINK-BAKE-011": 1,
  // beverages
  "BISL-BEVG-018": 1, "BOUR-BEVG-023": 1, "BRU-BEVG-008": 1, "COCA-BEVG-003": 1,
  "COCA-BEVG-011": 1, "FROO-BEVG-013": 1, "HAMD-BEVG-020": 1, "HORL-BEVG-022": 1,
  "KINL-BEVG-017": 1, "MAAZ-BEVG-014": 1, "NESC-BEVG-002": 1, "NESC-BEVG-009": 1,
  "PAPE-BEVG-016": 1, "REAL-BEVG-004": 1, "REAL-BEVG-015": 1, "RED-BEVG-005": 1,
  "RED-BEVG-019": 1, "SPRI-BEVG-012": 1, "TAJ-BEVG-006": 1, "TATA-BEVG-001": 1,
  "TEND-BEVG-021": 1, "TETL-BEVG-024": 1, "THUM-BEVG-010": 1, "WAGH-BEVG-007": 1,
  // condiments
  "AJWA-COND-012": 1, "BLAC-COND-013": 1, "CATC-COND-011": 1, "CHIN-COND-019": 1,
  "CHIN-COND-023": 1, "CHIN-COND-024": 1, "CLOV-COND-015": 1, "CUMI-COND-009": 1,
  "DABU-COND-020": 1, "EVER-COND-004": 1, "GREE-COND-014": 1, "KASU-COND-016": 1,
  "KISS-COND-003": 1, "KISS-COND-017": 1, "MAGG-COND-018": 1, "MDH-COND-002": 1,
  "MOTH-COND-001": 1, "MOTH-COND-021": 1, "MUST-COND-010": 1, "TATA-COND-005": 1,
  "TATA-COND-006": 1, "TATA-COND-007": 1, "TATA-COND-008": 1, "TOPS-COND-022": 1,
  // dairy
  "AMUL-DAIRY-001": 3, "AMUL-DAIRY-002": 1, "AMUL-DAIRY-003": 1, "AMUL-DAIRY-004": 1,
  "AMUL-DAIRY-005": 1, "AMUL-DAIRY-007": 1, "AMUL-DAIRY-008": 1, "AMUL-DAIRY-009": 1,
  "AMUL-DAIRY-010": 1, "AMUL-DAIRY-013": 1, "AMUL-DAIRY-014": 1, "AMUL-DAIRY-015": 1,
  "AMUL-DAIRY-016": 1, "AMUL-DAIRY-021": 1, "AMUL-DAIRY-023": 1, "BRIT-DAIRY-024": 1,
  "EPIG-DAIRY-019": 1, "GOWA-DAIRY-022": 1, "MILK-DAIRY-018": 1, "MOTH-DAIRY-011": 1,
  "MOTH-DAIRY-012": 1, "MOTH-DAIRY-017": 1, "NEST-DAIRY-006": 1, "NEST-DAIRY-020": 1,
  // electronics
  "APPL-ELEC-001": 9, "APPL-ELEC-002": 1, "APPL-ELEC-003": 1, "BOAT-ELEC-004": 1,
  "MI-ELEC-005": 1,
  // household
  "ARIE-HHLD-008": 1, "COLI-HHLD-013": 1, "COMF-HHLD-020": 1, "DETT-HHLD-023": 1,
  "FRES-HHLD-017": 1, "GARB-HHLD-019": 1, "GOOD-HHLD-015": 1, "HARP-HHLD-003": 1,
  "HARP-HHLD-012": 1, "HIT-HHLD-016": 1, "LIZO-HHLD-011": 1, "NIRM-HHLD-004": 1,
  "ODON-HHLD-021": 1, "ORIG-HHLD-018": 1, "PRIL-HHLD-024": 1, "RIN-HHLD-010": 1,
  "SCOT-HHLD-014": 1, "SCOT-HHLD-022": 1, "SURF-HHLD-001": 1, "SURF-HHLD-007": 1,
  "TIDE-HHLD-009": 1, "VIM-HHLD-002": 1, "VIM-HHLD-005": 1, "VIM-HHLD-006": 1,
  // personal_care
  "BAJA-PCAR-018": 1, "CETA-PCAR-026": 1, "CETA-PCAR-027": 1, "CLIN-PCAR-016": 1,
  "CLOS-PCAR-013": 1, "COLG-PCAR-001": 1, "COLG-PCAR-010": 1, "COLG-PCAR-011": 1,
  "DABU-PCAR-019": 1, "DERM-PCAR-030": 1, "DERM-PCAR-031": 1, "DETT-PCAR-002": 1,
  "DETT-PCAR-004": 1, "DETT-PCAR-009": 1, "DOVE-PCAR-006": 1, "FOGG-PCAR-025": 1,
  "GILL-PCAR-023": 1, "HEAD-PCAR-003": 1, "HEAD-PCAR-015": 1, "HIMA-PCAR-020": 1,
  "LIFE-PCAR-005": 1, "LIFE-PCAR-008": 1, "MINI-PCAR-028": 1, "MINI-PCAR-029": 1,
  "NIVE-PCAR-022": 1, "ORAL-PCAR-014": 1, "PANT-PCAR-017": 1, "PEAR-PCAR-007": 1,
  "SENS-PCAR-012": 1, "VASE-PCAR-021": 1, "WHIS-PCAR-024": 1,
  // produce
  "BABY-PROD-034": 1, "BANA-PROD-006": 1, "BEET-PROD-021": 1, "BITT-PROD-019": 1,
  "BOTT-PROD-018": 1, "BUTT-PROD-024": 1, "CABB-PROD-011": 1, "CARR-PROD-014": 1,
  "CAUL-PROD-010": 1, "COCO-PROD-022": 1, "CORI-PROD-007": 1, "CUCU-PROD-015": 1,
  "CUST-PROD-033": 1, "ELAI-PROD-032": 1, "GARL-PROD-005": 1, "GING-PROD-004": 1,
  "GREE-PROD-008": 1, "GREE-PROD-013": 1, "GREE-PROD-017": 1, "LADY-PROD-012": 1,
  "LEMO-PROD-009": 1, "MINT-PROD-020": 1, "NAGP-PROD-027": 1, "ONIO-PROD-001": 1,
  "PAPA-PROD-028": 1, "POME-PROD-026": 1, "POTA-PROD-003": 3, "ROYA-PROD-025": 1,
  "SEED-PROD-030": 1, "SPIN-PROD-016": 1, "SWEE-PROD-023": 1, "SWEE-PROD-029": 1,
  "TOMA-PROD-002": 3, "WATE-PROD-031": 1,
  // snacks
  "ACT-SNCK-019": 1, "BIKA-SNCK-020": 1, "BING-SNCK-018": 1, "BRIT-SNCK-002": 1,
  "BRIT-SNCK-008": 1, "BRIT-SNCK-009": 1, "BRIT-SNCK-021": 1, "CADB-SNCK-010": 1,
  "CADB-SNCK-030": 1, "CASH-SNCK-024": 1, "CHIN-SNCK-031": 1, "HALD-SNCK-003": 1,
  "HALD-SNCK-014": 1, "HALD-SNCK-015": 1, "HALD-SNCK-027": 1, "KELL-SNCK-006": 1,
  "KELL-SNCK-028": 1, "KISH-SNCK-025": 1, "KURK-SNCK-007": 1, "LAYS-SNCK-004": 1,
  "LAYS-SNCK-017": 1, "MAGG-SNCK-001": 1, "MAGG-SNCK-032": 1, "NEST-SNCK-011": 1,
  "OREO-SNCK-012": 1, "PARL-SNCK-005": 1, "PARL-SNCK-022": 1, "PHOO-SNCK-026": 1,
  "QUAK-SNCK-029": 1, "ROAS-SNCK-023": 1, "SUNF-SNCK-013": 1, "YIPP-SNCK-016": 1,
  // staples
  "AASH-STPL-002": 1, "AASH-STPL-019": 1, "BAMB-STPL-035": 1, "CHAN-STPL-005": 1,
  "COLD-STPL-007": 1, "DAAW-STPL-026": 1, "DHAR-STPL-030": 1, "EMAM-STPL-016": 1,
  "FORT-STPL-008": 1, "FORT-STPL-012": 1, "FORT-STPL-013": 1, "FORT-STPL-015": 1,
  "FORT-STPL-018": 1, "FORT-STPL-020": 1, "FORT-STPL-036": 1, "FREE-STPL-011": 1,
  "FREE-STPL-017": 1, "GEMI-STPL-014": 1, "INDI-STPL-001": 1, "JAGG-STPL-031": 1,
  "KABU-STPL-024": 1, "KALA-STPL-025": 1, "MADH-STPL-006": 1, "MAID-STPL-033": 1,
  "POHA-STPL-010": 1, "RAJM-STPL-009": 1, "SABU-STPL-034": 1, "SAFF-STPL-029": 1,
  "SONA-STPL-027": 1, "SOOJ-STPL-032": 1, "TATA-STPL-003": 1, "TATA-STPL-021": 1,
  "TATA-STPL-022": 1, "TATA-STPL-023": 1, "TATA-STPL-028": 1, "TOOR-STPL-004": 1,
};

/**
 * The stand-in for a SKU the merchant listed but nobody photographed.
 *
 * An inline data URI rather than a file, so it cannot itself 404 and cannot be mistaken
 * for a picture of the product. It is deliberately drawn as an empty frame: a buyer
 * should be able to tell at a glance that the shot is missing, not wonder whether the
 * thing they are buying really is a grey box.
 */
const PLACEHOLDER_SVG =
  '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 190 190">' +
  '<rect width="190" height="190" fill="#F8F8F8"/>' +
  '<rect x="47.5" y="57" width="95" height="76" rx="8" fill="none" stroke="#CCCCCC" stroke-width="3"/>' +
  '<circle cx="118" cy="80" r="7" fill="#CCCCCC"/>' +
  '<path d="M50 122l24-24 20 20 15-15 24 24" fill="none" stroke="#CCCCCC" stroke-width="3" ' +
  'stroke-linecap="round" stroke-linejoin="round"/></svg>';

export const PLACEHOLDER_IMAGE = `data:image/svg+xml;charset=utf-8,${encodeURIComponent(PLACEHOLDER_SVG)}`;

/**
 * Every local photograph for a SKU, best shot first.
 *
 * Returns a single-element array holding the placeholder when nothing is on disk, so a
 * gallery can iterate the result without a special case and always has something to show.
 */
export function imagesFor(sku: string): string[] {
  const count = VARIANT_COUNTS[sku];
  if (!count) return [PLACEHOLDER_IMAGE];
  const paths = [`/products/${sku}.webp`];
  for (let n = 2; n <= count; n += 1) paths.push(`/products/${sku}_${n}.webp`);
  return paths;
}

/** The one shot a card or a cart line uses. */
export function primaryImage(sku: string): string {
  return VARIANT_COUNTS[sku] ? `/products/${sku}.webp` : PLACEHOLDER_IMAGE;
}

/** Whether a real photograph exists, for a caller that wants to say so out loud. */
export function hasImage(sku: string): boolean {
  return Boolean(VARIANT_COUNTS[sku]);
}

/* ------------------------------------------------------------------ categories */

/**
 * The ten categories the merchant's catalogue is partitioned into, in the order the
 * storefront shows them. These slugs are the API's own: they go straight into
 * `api.products({ category })` and into the `/c/<category>` route.
 */
export const CATEGORIES = [
  "produce",
  "dairy",
  "staples",
  "snacks",
  "beverages",
  "bakery",
  "condiments",
  "household",
  "personal_care",
  "electronics",
] as const;

export type CategorySlug = (typeof CATEGORIES)[number];

/** The shop-front name for an aisle. The slug is the API's word; this is the buyer's. */
const CATEGORY_LABELS: Readonly<Record<string, string>> = {
  produce: "Fruits & Vegetables",
  dairy: "Dairy & Eggs",
  staples: "Atta, Rice & Dal",
  snacks: "Munchies & Snacks",
  beverages: "Cold Drinks & Juices",
  bakery: "Bakery & Biscuits",
  condiments: "Masala, Oil & Sauces",
  household: "Household Care",
  personal_care: "Personal Care",
  electronics: "Electronics",
};

/** Files that exist under `public/categories`, chosen to match each aisle's contents. */
const CATEGORY_IMAGES: Readonly<Record<string, string>> = {
  produce: "/categories/blinkit_produce.webp",
  dairy: "/categories/blinkit_dairy.webp",
  staples: "/categories/blinkit_staples.webp",
  snacks: "/categories/blinkit_snacks.webp",
  beverages: "/categories/blinkit_beverages.webp",
  bakery: "/categories/blinkit_bakery.webp",
  condiments: "/categories/blinkit_masalas.webp",
  household: "/categories/blinkit_household.webp",
  personal_care: "/categories/blinkit_personal_care.webp",
  electronics: "/categories/blinkit_home_office.webp",
};

export function categoryImage(category: string): string {
  return CATEGORY_IMAGES[category] ?? PLACEHOLDER_IMAGE;
}

/**
 * A readable name for a category slug, falling back to a de-slugged version of whatever
 * the server said. The server owns this vocabulary; an aisle this build has never heard
 * of must still render as itself rather than disappear.
 */
export function categoryLabel(category: string): string {
  const known = CATEGORY_LABELS[category];
  if (known) return known;
  return category
    .split(/[_-]/)
    .filter(Boolean)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}

/** True when the slug is one of the ten aisles this catalogue actually has. */
export function isKnownCategory(category: string): category is CategorySlug {
  return Object.prototype.hasOwnProperty.call(CATEGORY_IMAGES, category);
}

/**
 * The category a SKU belongs to, read from its middle segment.
 *
 * SKUs are `<PRODUCT>-<CATEGORY>-<NNN>`, and the segment is an abbreviation rather than
 * the slug. This is a lookup, not a guess: it is how a product page knows which aisle to
 * ask the catalogue for when all it has is a code out of the URL. An unrecognised segment
 * returns null so the caller can widen its search instead of querying a category that
 * does not exist.
 */
const SEGMENT_TO_CATEGORY: Readonly<Record<string, CategorySlug>> = {
  BAKE: "bakery",
  BEVG: "beverages",
  COND: "condiments",
  DAIRY: "dairy",
  ELEC: "electronics",
  HHLD: "household",
  PCAR: "personal_care",
  PROD: "produce",
  SNCK: "snacks",
  STPL: "staples",
};

export function categoryForSku(sku: string): CategorySlug | null {
  const segment = sku.split("-")[1];
  if (!segment) return null;
  return SEGMENT_TO_CATEGORY[segment.toUpperCase()] ?? null;
}
