"""refunds table and full payment status set

Revision ID: 1328a98c100c
Revises: c1d2f61e6eb9
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

from platform_db.rls import enable_rls_sql


revision = '1328a98c100c'
down_revision = 'c1d2f61e6eb9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refunds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('payment_attempt_id', sa.UUID(), nullable=False),
    sa.Column('checkout_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('idem_key', sa.String(length=128), nullable=False),
    sa.Column('provider_refund_id', sa.String(length=64), nullable=True),
    sa.Column('provider_originated', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('reason_code', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING','PROCESSED','FAILED','UNKNOWN','RECONCILING','ESCALATED')", name=op.f('ck_refunds_status_enum')),
    sa.CheckConstraint('amount_minor > 0', name=op.f('ck_refunds_amount_positive')),
    sa.ForeignKeyConstraint(['payment_attempt_id'], ['payment_attempts.id'], name=op.f('fk_refunds_payment_attempt_id')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_refunds_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refunds')),
    sa.UniqueConstraint('tenant_id', 'idem_key', name='refund_idem_unique_per_tenant')
    )
    # ### end Alembic commands ###


    # Autogenerate does not diff CHECK constraints, so the widened payment status set
    # is applied by hand. Without this the six refund states remain unpersistable.
    op.drop_constraint("status_enum", "payment_attempts", type_="check")
    op.create_check_constraint(
        "status_enum",
        "payment_attempts",
        "status IN ('CREATED','SUBMITTED','AUTHORIZED','CAPTURED','FAILED','EXPIRED',"
        "'UNKNOWN','RECONCILING','ESCALATED','STALE_CAPTURE',"
        "'AUTO_REFUND_PENDING','REFUND_PENDING','PARTIALLY_REFUNDED','REFUNDED',"
        "'REFUND_UNKNOWN','REFUND_FAILED')",
    )
    # New table is tenant-owned: it needs RLS and the kernel-only grant like every other.
    for statement in enable_rls_sql():
        if "refunds" in statement:
            op.execute(statement)
    op.execute("GRANT SELECT ON refunds TO commerce_app, commerce_kernel, commerce_worker;")
    op.execute("GRANT INSERT, UPDATE ON refunds TO commerce_kernel;")
    op.execute("REVOKE INSERT, UPDATE, DELETE ON refunds FROM commerce_app;")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refunds')
    # ### end Alembic commands ###
