"""transaction core schema

Revision ID: c1d2f61e6eb9
Revises:
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa

from platform_db.rls import all_statements, enable_rls_sql
from sqlalchemy.dialects import postgresql

revision = "c1d2f61e6eb9"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenants",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("home_region", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenants")),
        sa.UniqueConstraint("slug", name=op.f("uq_tenants_slug")),
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("aggregate_type", sa.String(length=48), nullable=False),
        sa.Column("aggregate_id", sa.UUID(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("actor_type", sa.String(length=32), nullable=False),
        sa.Column("actor_id", sa.String(length=128), nullable=True),
        sa.Column("principal_id", sa.String(length=128), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("prev_hash", sa.String(length=64), nullable=True),
        sa.Column("self_hash", sa.String(length=64), nullable=False),
        sa.Column("correlation_id", sa.UUID(), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("seq >= 1", name=op.f("ck_audit_events_seq_positive")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_audit_events_tenant_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
        sa.UniqueConstraint(
            "tenant_id",
            "aggregate_type",
            "aggregate_id",
            "seq",
            name=op.f("uq_audit_events_tenant_id_aggregate_type_aggregate_id_seq"),
        ),
    )
    op.create_index(
        "ix_audit_events_correlation", "audit_events", ["tenant_id", "correlation_id"], unique=False
    )
    op.create_table(
        "idempotency_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("idem_key", sa.String(length=128), nullable=False),
        sa.Column("operation", sa.String(length=48), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("response", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_idempotency_records_tenant_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_idempotency_records")),
        sa.UniqueConstraint(
            "tenant_id", "idem_key", name=op.f("uq_idempotency_records_tenant_id_idem_key")
        ),
    )
    op.create_table(
        "merchants",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_merchants_tenant_id"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_merchants")),
        sa.UniqueConstraint("tenant_id", "slug", name=op.f("uq_merchants_tenant_id_slug")),
    )
    op.create_table(
        "outbox_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("command_type", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'PENDING'"), nullable=False
        ),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("leased_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("correlation_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('PENDING','LEASED','DONE','FAILED','DEAD')",
            name=op.f("ck_outbox_events_status_enum"),
        ),
        sa.CheckConstraint("attempts >= 0", name=op.f("ck_outbox_events_attempts_non_negative")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_outbox_events_tenant_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_events")),
    )
    op.create_index("ix_outbox_ready", "outbox_events", ["status", "available_at"], unique=False)
    op.create_table(
        "payment_attempts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("checkout_id", sa.UUID(), nullable=False),
        sa.Column("checkout_version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("receipt", sa.String(length=40), nullable=False),
        sa.Column("provider_order_id", sa.String(length=64), nullable=True),
        sa.Column("provider_payment_id", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('CREATED','SUBMITTED','AUTHORIZED','CAPTURED','FAILED','EXPIRED','UNKNOWN','RECONCILING','ESCALATED','STALE_CAPTURE')",
            name=op.f("ck_payment_attempts_status_enum"),
        ),
        sa.CheckConstraint("amount_minor > 0", name=op.f("ck_payment_attempts_amount_positive")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_payment_attempts_tenant_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_attempts")),
        sa.UniqueConstraint("tenant_id", "receipt", name="receipt_unique_per_tenant"),
    )
    op.create_index(
        "uq_payment_attempts_one_non_terminal",
        "payment_attempts",
        ["tenant_id", "checkout_id"],
        unique=True,
        postgresql_where=sa.text(
            "status IN ('CREATED','SUBMITTED','AUTHORIZED','UNKNOWN','RECONCILING')"
        ),
    )
    op.create_table(
        "platform_operating_modes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=True),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("reason_code", sa.String(length=64), nullable=False),
        sa.Column("actor", sa.Text(), nullable=False),
        sa.Column(
            "changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "mode IN ('NORMAL','SAFE_MODE')", name=op.f("ck_platform_operating_modes_mode_enum")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_platform_operating_modes_tenant_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platform_operating_modes")),
    )
    op.create_index(
        "ix_operating_modes_lookup",
        "platform_operating_modes",
        ["tenant_id", "changed_at"],
        unique=False,
    )
    op.create_table(
        "reservations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("checkout_id", sa.UUID(), nullable=False),
        sa.Column("checkout_version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE','CONSUMED','RELEASED','EXPIRED')",
            name=op.f("ck_reservations_status_enum"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_reservations_tenant_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reservations")),
    )
    op.create_index(
        "ix_reservations_checkout",
        "reservations",
        ["tenant_id", "checkout_id", "checkout_version"],
        unique=False,
    )
    op.create_table(
        "delegated_authorities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("merchant_id", sa.UUID(), nullable=False),
        sa.Column("buyer_ref", sa.String(length=128), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("revocation_epoch", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("max_amount_minor", sa.BigInteger(), nullable=False),
        sa.Column(
            "consumed_amount_minor", sa.BigInteger(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('SINGLE_USE','RESERVE')", name=op.f("ck_delegated_authorities_kind_enum")
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE','EXHAUSTED','EXPIRED','REVOKED','RECONCILING')",
            name=op.f("ck_delegated_authorities_status_enum"),
        ),
        sa.CheckConstraint(
            "consumed_amount_minor <= max_amount_minor",
            name=op.f("ck_delegated_authorities_consumed_within_max"),
        ),
        sa.CheckConstraint(
            "consumed_amount_minor >= 0",
            name=op.f("ck_delegated_authorities_consumed_non_negative"),
        ),
        sa.CheckConstraint(
            "max_amount_minor >= 0", name=op.f("ck_delegated_authorities_max_amount_non_negative")
        ),
        sa.CheckConstraint(
            "revocation_epoch >= 0", name=op.f("ck_delegated_authorities_epoch_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"], ["merchants.id"], name=op.f("fk_delegated_authorities_merchant_id")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_delegated_authorities_tenant_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_delegated_authorities")),
    )
    op.create_table(
        "execution_grants",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("checkout_id", sa.UUID(), nullable=False),
        sa.Column("checkout_version", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("payment_attempt_id", sa.UUID(), nullable=True),
        sa.Column("operation", sa.String(length=32), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("kernel_decision_id", sa.UUID(), nullable=False),
        sa.Column("outbox_command_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "issued_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "operation IN ('PAYMENT_CREATE_ORDER','REFUND_EXECUTE','RESERVE_DEBIT')",
            name=op.f("ck_execution_grants_operation_enum"),
        ),
        sa.CheckConstraint(
            "status IN ('ISSUED','CONSUMED','EXPIRED','REVOKED')",
            name=op.f("ck_execution_grants_status_enum"),
        ),
        sa.CheckConstraint("amount_minor > 0", name=op.f("ck_execution_grants_amount_positive")),
        sa.ForeignKeyConstraint(
            ["payment_attempt_id"],
            ["payment_attempts.id"],
            name=op.f("fk_execution_grants_payment_attempt_id"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_execution_grants_tenant_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_execution_grants")),
    )
    op.create_index(
        "uq_execution_grants_one_active_per_attempt",
        "execution_grants",
        ["tenant_id", "payment_attempt_id"],
        unique=True,
        postgresql_where=sa.text("status = 'ISSUED'"),
    )
    op.create_table(
        "policy_at_sale_receipts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("merchant_id", sa.UUID(), nullable=False),
        sa.Column("checkout_id", sa.UUID(), nullable=False),
        sa.Column("checkout_version", sa.Integer(), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("receipt_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"], ["merchants.id"], name=op.f("fk_policy_at_sale_receipts_merchant_id")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_policy_at_sale_receipts_tenant_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_policy_at_sale_receipts")),
        sa.UniqueConstraint(
            "tenant_id",
            "checkout_id",
            "checkout_version",
            name=op.f("uq_policy_at_sale_receipts_tenant_id_checkout_id_checkout_version"),
        ),
    )
    op.create_table(
        "approvals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("checkout_id", sa.UUID(), nullable=False),
        sa.Column("checkout_version", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("policy_receipt_hash", sa.String(length=64), nullable=True),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("authority_id", sa.UUID(), nullable=True),
        sa.Column("authority_epoch", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "issued_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('RECORDED','CONSUMED','INVALIDATED','EXPIRED')",
            name=op.f("ck_approvals_status_enum"),
        ),
        sa.CheckConstraint("amount_minor >= 0", name=op.f("ck_approvals_amount_non_negative")),
        sa.ForeignKeyConstraint(
            ["authority_id"], ["delegated_authorities.id"], name=op.f("fk_approvals_authority_id")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_approvals_tenant_id"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approvals")),
        sa.UniqueConstraint(
            "tenant_id",
            "checkout_id",
            "checkout_version",
            "status",
            name="one_live_approval_per_version",
        ),
    )
    op.create_table(
        "checkout_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("merchant_id", sa.UUID(), nullable=False),
        sa.Column("checkout_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("total_minor", sa.BigInteger(), nullable=False),
        sa.Column("policy_receipt_id", sa.UUID(), nullable=True),
        sa.Column("policy_receipt_hash", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=48), nullable=False),
        sa.Column("immutable", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("invalidated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('DRAFT','QUOTED','RESERVED','APPROVAL_REQUIRED','APPROVED','EXECUTION_PENDING','AWAITING_PAYMENT','PAID','PAYMENT_FAILED','PAYMENT_UNKNOWN','INVALIDATED','INVALIDATED_AWAITING_PAYMENT_RESULT','CANCELLED','EXPIRED')",
            name=op.f("ck_checkout_versions_status_enum"),
        ),
        sa.CheckConstraint(
            "total_minor >= 0", name=op.f("ck_checkout_versions_total_non_negative")
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_checkout_versions_version_positive")),
        sa.ForeignKeyConstraint(
            ["merchant_id"], ["merchants.id"], name=op.f("fk_checkout_versions_merchant_id")
        ),
        sa.ForeignKeyConstraint(
            ["policy_receipt_id"],
            ["policy_at_sale_receipts.id"],
            name=op.f("fk_checkout_versions_policy_receipt_id"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_checkout_versions_tenant_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_checkout_versions")),
        sa.UniqueConstraint(
            "tenant_id",
            "checkout_id",
            "version",
            name=op.f("uq_checkout_versions_tenant_id_checkout_id_version"),
        ),
    )
    op.create_index(
        "ix_checkout_versions_current",
        "checkout_versions",
        ["tenant_id", "checkout_id", "version"],
        unique=False,
    )
    # ### end Alembic commands ###

    # Row-level security, roles and least-privilege grants. Applied in the same
    # migration as the tables so that no window exists where a tenant-owned table
    # is queryable without a policy.
    for statement in all_statements():
        op.execute(statement)


def downgrade() -> None:
    for statement in enable_rls_sql():
        if statement.startswith("CREATE POLICY"):
            continue
    # policies vanish with their tables below
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_checkout_versions_current", table_name="checkout_versions")
    op.drop_table("checkout_versions")
    op.drop_table("approvals")
    op.drop_table("policy_at_sale_receipts")
    op.drop_index(
        "uq_execution_grants_one_active_per_attempt",
        table_name="execution_grants",
        postgresql_where=sa.text("status = 'ISSUED'"),
    )
    op.drop_table("execution_grants")
    op.drop_table("delegated_authorities")
    op.drop_index("ix_reservations_checkout", table_name="reservations")
    op.drop_table("reservations")
    op.drop_index("ix_operating_modes_lookup", table_name="platform_operating_modes")
    op.drop_table("platform_operating_modes")
    op.drop_index(
        "uq_payment_attempts_one_non_terminal",
        table_name="payment_attempts",
        postgresql_where=sa.text(
            "status IN ('CREATED','SUBMITTED','AUTHORIZED','UNKNOWN','RECONCILING')"
        ),
    )
    op.drop_table("payment_attempts")
    op.drop_index("ix_outbox_ready", table_name="outbox_events")
    op.drop_table("outbox_events")
    op.drop_table("merchants")
    op.drop_table("idempotency_records")
    op.drop_index("ix_audit_events_correlation", table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_table("tenants")
    # ### end Alembic commands ###
