"""service tables

Revision ID: c6ffa021cbb0
Revises: 1328a98c100c
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'c6ffa021cbb0'
down_revision = '1328a98c100c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenario_faults',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('checkout_id', sa.UUID(), nullable=True),
    sa.Column('payment_attempt_id', sa.UUID(), nullable=True),
    sa.Column('armed', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_scenario_faults_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenario_faults'))
    )
    op.create_index('ix_scenario_faults_tenant_armed', 'scenario_faults', ['tenant_id', 'armed'], unique=False)
    op.create_table('webhook_inbox',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('dedup_key', sa.String(length=160), nullable=False),
    sa.Column('provider_event_id', sa.String(length=64), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('body_digest', sa.String(length=64), nullable=False),
    sa.Column('raw_body', sa.LargeBinary(), nullable=False),
    sa.Column('headers_redacted', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('signature_verified', sa.Boolean(), nullable=False),
    sa.Column('payment_id', sa.String(length=64), nullable=True),
    sa.Column('order_id', sa.String(length=64), nullable=True),
    sa.Column('refund_id', sa.String(length=64), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('apply_status', sa.String(length=16), server_default=sa.text("'RECEIVED'"), nullable=False),
    sa.Column('apply_reason', sa.String(length=64), nullable=True),
    sa.Column('state_before', sa.String(length=24), nullable=True),
    sa.Column('state_after', sa.String(length=24), nullable=True),
    sa.Column('changed', sa.Boolean(), nullable=True),
    sa.Column('duplicate_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('outbox_command_id', sa.UUID(), nullable=True),
    sa.CheckConstraint("apply_status IN ('RECEIVED','APPLIED','IGNORED','FAILED')", name=op.f('ck_webhook_inbox_apply_status_enum')),
    sa.CheckConstraint('duplicate_count >= 0', name=op.f('ck_webhook_inbox_duplicate_count_non_negative')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_webhook_inbox_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_inbox')),
    sa.UniqueConstraint('tenant_id', 'dedup_key', name=op.f('uq_webhook_inbox_tenant_id_dedup_key'))
    )
    op.create_index('ix_webhook_inbox_tenant_order', 'webhook_inbox', ['tenant_id', 'order_id'], unique=False)
    op.create_index('ix_webhook_inbox_tenant_payment', 'webhook_inbox', ['tenant_id', 'payment_id'], unique=False)
    op.create_table('api_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('buyer_ref', sa.String(length=128), nullable=False),
    sa.Column('actor_type', sa.String(length=32), nullable=False),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("actor_type IN ('BUYER','AGENT','OPERATOR')", name=op.f('ck_api_sessions_actor_type_enum')),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], name=op.f('fk_api_sessions_merchant_id')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_api_sessions_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_api_sessions_token_hash'))
    )
    op.create_index('ix_api_sessions_tenant_buyer', 'api_sessions', ['tenant_id', 'buyer_ref'], unique=False)
    op.create_table('baskets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('buyer_ref', sa.String(length=128), nullable=False),
    sa.Column('lines', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('quote', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('catalogue_revision', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'OPEN'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('OPEN','CHECKED_OUT','ABANDONED')", name=op.f('ck_baskets_status_enum')),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], name=op.f('fk_baskets_merchant_id')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_baskets_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_baskets'))
    )
    op.create_index('ix_baskets_tenant_buyer', 'baskets', ['tenant_id', 'buyer_ref'], unique=False)
    op.create_table('scenario_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('injection_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('audit_event_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], name=op.f('fk_scenario_runs_merchant_id')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_scenario_runs_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenario_runs'))
    )
    op.create_index('ix_scenario_runs_tenant_merchant', 'scenario_runs', ['tenant_id', 'merchant_id'], unique=False)
    op.create_table('checkouts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('basket_id', sa.UUID(), nullable=False),
    sa.Column('buyer_ref', sa.String(length=128), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=48), nullable=False),
    sa.Column('correlation_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT','QUOTED','RESERVED','APPROVAL_REQUIRED','APPROVED','EXECUTION_PENDING','AWAITING_PAYMENT','PAID','PAYMENT_FAILED','PAYMENT_UNKNOWN','INVALIDATED','INVALIDATED_AWAITING_PAYMENT_RESULT','CANCELLED','EXPIRED')", name=op.f('ck_checkouts_status_enum')),
    sa.CheckConstraint('current_version >= 1', name=op.f('ck_checkouts_current_version_positive')),
    sa.ForeignKeyConstraint(['basket_id'], ['baskets.id'], name=op.f('fk_checkouts_basket_id')),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], name=op.f('fk_checkouts_merchant_id')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_checkouts_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checkouts')),
    sa.UniqueConstraint('tenant_id', 'basket_id', name=op.f('uq_checkouts_tenant_id_basket_id'))
    )
    op.create_index('ix_checkouts_tenant_buyer', 'checkouts', ['tenant_id', 'buyer_ref'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('checkout_id', sa.UUID(), nullable=False),
    sa.Column('checkout_version', sa.Integer(), nullable=False),
    sa.Column('payment_attempt_id', sa.UUID(), nullable=False),
    sa.Column('policy_receipt_id', sa.UUID(), nullable=False),
    sa.Column('policy_receipt_hash', sa.String(length=64), nullable=False),
    sa.Column('total_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('capture_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('CONFIRMED','FULFILMENT_BLOCKED','CANCELLED','PARTIALLY_REFUNDED','REFUNDED')", name=op.f('ck_orders_status_enum')),
    sa.CheckConstraint('checkout_version >= 1', name=op.f('ck_orders_checkout_version_positive')),
    sa.CheckConstraint('total_minor >= 0', name=op.f('ck_orders_total_non_negative')),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], name=op.f('fk_orders_merchant_id')),
    sa.ForeignKeyConstraint(['payment_attempt_id'], ['payment_attempts.id'], name=op.f('fk_orders_payment_attempt_id')),
    sa.ForeignKeyConstraint(['policy_receipt_id'], ['policy_at_sale_receipts.id'], name=op.f('fk_orders_policy_receipt_id')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_orders_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('tenant_id', 'payment_attempt_id', name=op.f('uq_orders_tenant_id_payment_attempt_id'))
    )
    op.create_index('ix_orders_tenant_checkout', 'orders', ['tenant_id', 'checkout_id'], unique=False)
    op.create_table('provider_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('payment_attempt_id', sa.UUID(), nullable=False),
    sa.Column('grant_id', sa.UUID(), nullable=True),
    sa.Column('refund_id', sa.UUID(), nullable=True),
    sa.Column('operation', sa.String(length=32), nullable=False),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('body_hash', sa.String(length=64), nullable=False),
    sa.Column('header_names', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('request_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('provider_id', sa.String(length=64), nullable=True),
    sa.Column('outcome_code', sa.String(length=48), nullable=False),
    sa.Column('provider_error_code', sa.String(length=128), nullable=True),
    sa.Column('response_digest', sa.String(length=64), nullable=True),
    sa.Column('transport_error', sa.String(length=64), nullable=True),
    sa.CheckConstraint('http_status IS NULL OR http_status BETWEEN 100 AND 599', name=op.f('ck_provider_requests_http_status_range')),
    sa.ForeignKeyConstraint(['grant_id'], ['execution_grants.id'], name=op.f('fk_provider_requests_grant_id')),
    sa.ForeignKeyConstraint(['payment_attempt_id'], ['payment_attempts.id'], name=op.f('fk_provider_requests_payment_attempt_id')),
    sa.ForeignKeyConstraint(['refund_id'], ['refunds.id'], name=op.f('fk_provider_requests_refund_id')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_provider_requests_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_requests'))
    )
    op.create_index('ix_provider_requests_tenant_attempt', 'provider_requests', ['tenant_id', 'payment_attempt_id'], unique=False)
    op.create_index('ix_provider_requests_tenant_grant', 'provider_requests', ['tenant_id', 'grant_id'], unique=False)
    op.create_table('reconciliation_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('payment_attempt_id', sa.UUID(), nullable=False),
    sa.Column('refund_id', sa.UUID(), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('identifiers_queried', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_evidence_digest', sa.String(length=64), nullable=True),
    sa.Column('decision', sa.String(length=64), nullable=False),
    sa.Column('resulting_transition', sa.String(length=64), nullable=True),
    sa.Column('next_scheduled_attempt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('correlation_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('attempt_number >= 1', name=op.f('ck_reconciliation_runs_attempt_number_positive')),
    sa.ForeignKeyConstraint(['payment_attempt_id'], ['payment_attempts.id'], name=op.f('fk_reconciliation_runs_payment_attempt_id')),
    sa.ForeignKeyConstraint(['refund_id'], ['refunds.id'], name=op.f('fk_reconciliation_runs_refund_id')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_reconciliation_runs_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reconciliation_runs')),
    sa.UniqueConstraint('tenant_id', 'payment_attempt_id', 'reason', 'attempt_number', name=op.f('uq_reconciliation_runs_tenant_id_payment_attempt_id_reason_attempt_number'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reconciliation_runs')
    op.drop_index('ix_provider_requests_tenant_grant', table_name='provider_requests')
    op.drop_index('ix_provider_requests_tenant_attempt', table_name='provider_requests')
    op.drop_table('provider_requests')
    op.drop_index('ix_orders_tenant_checkout', table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_checkouts_tenant_buyer', table_name='checkouts')
    op.drop_table('checkouts')
    op.drop_index('ix_scenario_runs_tenant_merchant', table_name='scenario_runs')
    op.drop_table('scenario_runs')
    op.drop_index('ix_baskets_tenant_buyer', table_name='baskets')
    op.drop_table('baskets')
    op.drop_index('ix_api_sessions_tenant_buyer', table_name='api_sessions')
    op.drop_table('api_sessions')
    op.drop_index('ix_webhook_inbox_tenant_payment', table_name='webhook_inbox')
    op.drop_index('ix_webhook_inbox_tenant_order', table_name='webhook_inbox')
    op.drop_table('webhook_inbox')
    op.drop_index('ix_scenario_faults_tenant_armed', table_name='scenario_faults')
    op.drop_table('scenario_faults')
    # ### end Alembic commands ###
