// Generated by scripts/generate_voice_wire.py. Do not edit by hand.

export const VOICE_PROTOCOL_VERSION = 2 as const;

export const DEGRADATION_KINDS = ["stt_connection_lost", "stt_rotation_failed", "stt_unavailable", "tts_failed", "reasoning_failed", "echo_gate_uncertain", "speech_guard_refused", "stale_turn_dropped", "card_unavailable"] as const;

export type AgentReply = {
  "type": "agent_reply";
  "intent_id": number | null;
  "unspoken": boolean;
  "text": string;
  "deterministic": boolean;
  "locale": string;
  "turn_id": number;
  "speech_generation": number;
  "template_id": string | null;
  "template_version": number | null;
  "fields": Record<string, string> | null;
  "offer": Record<string, unknown> | null;
  "offer_is_proposal": boolean;
  "support_order_id": string | null;
  "items": Array<Record<string, unknown>> | null;
};

export type AudioContract = {
  "sample_rate_hz": number;
  "encoding": "pcm16le";
  "channels": 1;
};

export type BargeIn = {
  "type": "barge_in";
  "reason": "speak" | "cancel";
};

export type CardRead = {
  "type": "card_read";
  "checkout_id": string;
  "version": number;
  "content_hash": string;
  "amount_minor": number;
  "currency": string;
  "locale": string;
  "template_id": string;
  "template_version": number;
  "speech_generation": number;
};

export type CartUpdated = {
  "type": "cart_updated";
  "cart_id": string;
  "event_id": string;
};

export type CheckoutGuidance = {
  "type": "checkout_guidance";
  "checkout_id": string | null;
  "version": number | null;
  "stage": "review" | "reserve-review" | "manual" | "verifying" | "success" | "failed" | "bill-details";
};

export type ConsentClosed = {
  "type": "consent_closed";
  "consent_id": string;
  "reason": "recognised" | "declined" | "expired" | "barge_in" | "superseded";
};

export type ConsentDeclined = {
  "type": "consent_declined";
  "consent_id": string;
  "heard": string;
};

export type ConsentListening = {
  "type": "consent_listening";
  "consent_id": string;
  "closes_in_s": number;
  "speech_generation": number;
};

export type ConsentRecognised = {
  "type": "consent_recognised";
  "consent_id": string;
  "checkout_id": string;
  "version": number;
  "content_hash": string;
  "amount_minor": number;
  "currency": string;
  "heard": string;
  "turn_id": number;
  "stt_generation": number;
  "offset_ms": number;
  "recorded": false;
  "voice_is_authority": false;
};

export type ConsentUnrecognised = {
  "type": "consent_unrecognised";
  "consent_id": string;
  "text": string;
  "reason": "not_in_lexicon" | "began_before_reading_ended";
};

export type Degradation = {
  "type": "degradation";
  "kind": "stt_connection_lost" | "stt_rotation_failed" | "stt_unavailable" | "tts_failed" | "reasoning_failed" | "echo_gate_uncertain" | "speech_guard_refused" | "stale_turn_dropped" | "card_unavailable";
  "message": string;
  "text_input_available": true;
  "transaction_state_changed": false;
};

export type ErrorFrame = {
  "type": "error";
  "code": string;
  "message": string;
};

export type IntentOutcome = "answered" | "empty" | "superseded" | "cancelled" | "failed" | "stale" | "routed_to_checkout" | "disconnected";

export type Interrupted = {
  "type": "interrupted";
  "speech_generation": number;
};

export type Ping = {
  "type": "ping";
};

export type PlaybackEnded = {
  "type": "playback_ended";
  "utterance_id": number;
  "speech_generation": number;
};

export type PlaybackStarted = {
  "type": "playback_started";
  "utterance_id": number;
  "speech_generation": number;
};

export type Pong = {
  "type": "pong";
};

export type ReadCard = {
  "type": "read_card";
  "checkout_id": string;
  "version": number;
  "locale": "en-IN" | "hi-IN";
};

export type RecognitionState = {
  "type": "recognition_state";
  "state": "connecting" | "ready" | "unavailable";
};

export type ScreenContext = {
  "type": "screen_context";
  "scope": "shopping" | "checkout";
};

export type SessionReady = {
  "type": "session_ready";
  "session_id": string;
  "protocol_version": 2;
  "input": AudioContract;
  "output": AudioContract;
  "mic_frame_ms": number;
  "echo_tail_s": number;
  "barge_in_level_rms": number;
  "barge_in_sustain_s": number;
  "playback_lead_s": number;
  "voice_is_authority": false;
};

export type SpeechChunkHeader = {
  "type": "speech_chunk";
  "seq": number;
  "utterance_id": number;
  "speech_generation": number;
  "text": string;
  "sample_rate_hz": number;
  "byte_length": number;
  "deterministic": boolean;
  "encoding": "pcm16le";
};

export type SpeechEnd = {
  "type": "speech_end";
  "utterance_id": number;
  "speech_generation": number;
  "chunks": number;
  "cancelled": boolean;
};

export type SpeechStart = {
  "type": "speech_start";
  "utterance_id": number;
  "speech_generation": number;
};

export type TextInput = {
  "type": "text_input";
  "text": string;
};

export type TranscriptFinal = {
  "type": "transcript_final";
  "text": string;
  "turn_id": number;
  "stt_generation": number;
  "age_ms": number;
  "stale": boolean;
  "source": "voice" | "text";
  "cumulative": true;
  "revisable": false;
  "empty_means": "keep_held";
};

export type TranscriptPartial = {
  "type": "transcript_partial";
  "text": string;
  "turn_id": number;
  "stt_generation": number;
  "age_ms": number;
  "cumulative": true;
  "revisable": true;
  "empty_means": "keep_held";
};

export type TurnClosed = {
  "type": "turn_closed";
  "intent_id": number;
  "turn_id": number;
  "outcome": IntentOutcome;
};

export type TurnOpened = {
  "type": "turn_opened";
  "intent_id": number;
  "turn_id": number;
  "source": string;
};

export type TurnReasoning = {
  "type": "turn_reasoning";
  "intent_id": number;
};

export type ServerFrame = SessionReady | RecognitionState | TranscriptPartial | TranscriptFinal | AgentReply | SpeechStart | SpeechChunkHeader | SpeechEnd | Interrupted | Degradation | ErrorFrame | CardRead | ConsentListening | ConsentRecognised | ConsentDeclined | ConsentUnrecognised | ConsentClosed | TurnOpened | TurnReasoning | TurnClosed | Pong;

export type ClientFrame = TextInput | BargeIn | PlaybackStarted | PlaybackEnded | Ping | ReadCard | CheckoutGuidance | CartUpdated | ScreenContext;
