'use client';
import {useState,useEffect} from 'react';
import {MapPin,Store,UserRound,Settings2,Check} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from './ui/dialog';
const initial={name:'Vedant',email:'',address:'',city:'Bengaluru',language:'English'};
export function AccountControls(){
 const [panel,setPanel]=useState<'address'|'store'|'profile'|'settings'|null>(null);const [saved,setSaved]=useState(initial);const [draft,setDraft]=useState(initial);const [notice,setNotice]=useState('');
 useEffect(()=>{try{const raw=JSON.parse(localStorage.getItem('razorsharp-profile-demo')||'null');if(raw&&Object.keys(initial).every(k=>typeof raw[k]==='string')){setSaved(raw);setDraft(raw)}}catch{}},[]);
 const open=(next:typeof panel)=>{setDraft(saved);setNotice('');setPanel(next)};
 const save=()=>{try{localStorage.setItem('razorsharp-profile-demo',JSON.stringify(draft));setSaved(draft);setNotice('Saved in this browser only.')}catch{setNotice('Could not save. Browser storage is unavailable.')}};
 return <><nav className="account-controls" aria-label="Delivery and account"><button onClick={()=>open('address')} aria-label="Delivery address" title="Delivery address"><MapPin size={18}/><span>{saved.address?'Your address':'Add address'}</span></button><button onClick={()=>open('store')} aria-label="Store location" title="Store location"><Store size={18}/></button><button onClick={()=>open('profile')} aria-label="Your profile" title="Your profile"><UserRound size={18}/></button><button onClick={()=>open('settings')} aria-label="Account settings" title="Account settings"><Settings2 size={18}/></button></nav>
 <Dialog open={!!panel} onOpenChange={v=>!v&&setPanel(null)}><DialogContent className="concept-dialog account-dialog"><DialogHeader><DialogTitle>{panel==='address'?'Where should your essentials go?':panel==='store'?'Your neighbourhood store.':panel==='profile'?'Your profile.':'Your preferences.'}</DialogTitle><DialogDescription>Local design preview · not connected to a delivery or account service.</DialogDescription></DialogHeader>
 {panel==='address'?<><label className="form-field">Delivery address<textarea rows={3} maxLength={350} value={draft.address} onChange={e=>setDraft({...draft,address:e.target.value})} placeholder="House or flat, building, street and area"/></label><label className="form-field">City<input maxLength={80} value={draft.city} onChange={e=>setDraft({...draft,city:e.target.value})}/></label><p className="muted">Use sample details. Delivery availability, fees and checkout address binding are not connected.</p><button className="primary" disabled={!draft.address.trim()||!draft.city.trim()} onClick={save}>Save sample address <Check size={15}/></button></>:panel==='store'?<><div className="account-store"><Store size={30}/><div><h3>Green Basket</h3><p>Indiranagar, Bengaluru</p><span>Sample store location</span></div></div><p className="muted">This is the store used by the mock catalogue. Live location, store switching and service-area checks are not connected.</p><button className="secondary" onClick={()=>open('address')}><MapPin size={15}/> Review delivery address</button></>:panel==='profile'?<><label className="form-field">Display name<input maxLength={60} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label className="form-field">Sample email (optional)<input type="email" maxLength={120} value={draft.email} onChange={e=>setDraft({...draft,email:e.target.value})} placeholder="you@example.com"/></label><p className="muted">These fields customise the local preview; they do not create or update an authenticated account.</p><button className="primary" disabled={!draft.name.trim()} onClick={save}>Save profile preview <Check size={15}/></button></>:<><label className="form-field">Preferred language<select value={draft.language} onChange={e=>setDraft({...draft,language:e.target.value})}><option>English</option><option>Hindi</option><option>Hinglish</option></select></label><p className="muted">Language selection is saved for preview only. It does not change the model or voice language yet. Use the header motion control to pause animations.</p><button className="primary" onClick={save}>Save preference</button><button className="subtle" onClick={()=>{try{localStorage.removeItem('razorsharp-profile-demo');setSaved(initial);setDraft(initial);setNotice('Local profile and address reset.')}catch{setNotice('Unable to reset local data.')}}}>Reset local profile and address</button></>}
 {notice&&<p className="account-notice" role="status">{notice}</p>}</DialogContent></Dialog></>;
}
