'use client';
import {CampaignArtwork} from './campaign-artwork';
import {useRef,useState,useEffect} from 'react';
import {ArrowLeft,ArrowRight,Sparkles} from 'lucide-react';
const key='razorsharp-storefront-campaign-v1';
type Campaign={title:string;body:string};
function read():Campaign|null{try{const v=JSON.parse(localStorage.getItem(key)||'null');return v&&typeof v.title==='string'&&typeof v.body==='string'?v:null}catch{return null}}
export function CampaignPlacement(){
 const [title,setTitle]=useState('Your weekend, freshly picked.');const [body,setBody]=useState('Explore milk, bread and fresh fruit for a better morning.');const [review,setReview]=useState(false);const [published,setPublished]=useState<Campaign|null>(null);const [error,setError]=useState('');
 useEffect(()=>setPublished(read()),[]);
 return <section className="panel placement-editor"><div className="placement-stagebar"><span className="active">01 Draft</span><span className={review?'active':''}>02 Review</span><span className={published?'active':''}>03 Published</span></div><span className="section-eyebrow">SHOPPING COPILOT PLACEMENT · LOCAL DEMO</span><h3>Meet customers where they discover.</h3><p className="muted">Publish a labelled merchant promotion to the buyer’s discovery cards. This local preview does not send email or change prices or Merchant Policy.</p><label className="form-field">Campaign headline<input maxLength={80} value={title} onChange={e=>{setTitle(e.target.value);setReview(false)}}/></label><label className="form-field">Campaign message<textarea rows={2} maxLength={220} value={body} onChange={e=>{setBody(e.target.value);setReview(false)}}/></label><div className="campaign-connection"><span><b>{review?'Review this exact placement':'Your customer’s view'}</b>The same card appears in the shopping conversation.</span><ArrowRight size={18}/></div><CampaignArtwork title={title} body={body}/><p className="muted">Preview · the customer button opens a breakfast selection. No discount is applied by this placement.</p><div className="placement-actions"><button className="primary" disabled={!title.trim()||!body.trim()} onClick={()=>{if(!review){setReview(true);return}try{localStorage.setItem(key,JSON.stringify({title,body}));setPublished({title,body});setReview(false);setError('');window.dispatchEvent(new Event('campaign:updated'))}catch{setError('Browser storage is unavailable. The promotion was not published.')}}}>{review?'Approve & publish local preview':'Review placement'} <ArrowRight size={15}/></button>{published&&<><a className="secondary" href="/shop#campaign">View buyer placement</a><button className="subtle" onClick={()=>{try{localStorage.removeItem(key);setPublished(null);window.dispatchEvent(new Event('campaign:updated'));setError('')}catch{setError('Could not remove the local promotion.')}}}>Unpublish</button></>}</div><p role="status" className="muted">{error|| (published?`Published locally: ${published.title}`:'No merchant promotion published.')}</p></section>
}
export function DiscoveryCards({onAsk,merchant=false}:{onAsk:(text:string)=>void;merchant?:boolean}){
 const rail=useRef<HTMLDivElement>(null);const [campaign,setCampaign]=useState<Campaign|null>(null);
 useEffect(()=>{const update=()=>setCampaign(read());update();window.addEventListener('storage',update);window.addEventListener('campaign:updated',update);return()=>{window.removeEventListener('storage',update);window.removeEventListener('campaign:updated',update)}},[]);
 const cards=merchant?[
 ['GROWTH ANALYST','Find your next opportunity.','Understand what customers buy and what to try next.','What is driving this week’s growth?','NESC-BEVG-002'],
 ['OPERATIONS ASSISTANT','Keep favourites in stock.','Spot inventory that needs your attention.','Which products need restocking?','AMUL-DAIRY-001'],
 ['CAMPAIGN BUILDER','A reason to come back.','Draft a thoughtful campaign for your customers.','Draft a weekend breakfast campaign','BRIT-BAKE-001']
 ]:[
 ['SHOPPING SPECIALIST','A better breakfast.','Build a cart around your morning and your budget.','Breakfast for two, under ₹500','BRIT-BAKE-001'],
 ['PRODUCT DISCOVERY','Fresh finds, less searching.','Explore fruit and everyday produce in conversation.','Show me fresh fruit','NAGP-PROD-027'],
 ['COMPARISON HELP','Find your everyday favourite.','Explore coffee choices and compare sample prices.','Help me choose coffee','NESC-BEVG-002'],
 ['SUPPORT DESK','Help after the purchase.','Follow an order or review an item that arrived damaged.','Help with a damaged item','AMUL-DAIRY-001']
 ];
 const scroll=(n:number)=>{const node=rail.current;if(node)node.scrollBy({left:n*node.clientWidth*.8,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches||document.documentElement.dataset.motion==='paused'?'instant':'smooth'})};
 return <section className={`discovery-cards ${merchant?'discovery-compact':''}`} aria-label={merchant?'Ways your business copilot can help':'Explore shopping help and sample categories'}><div className="discovery-heading"><span><Sparkles size={13}/> {merchant?'A TEAM BEHIND YOUR NEXT MOVE':'ONE CONVERSATION. A LITTLE MORE POSSIBILITY.'}</span><div><button aria-label="Previous suggestions" onClick={()=>scroll(-1)}><ArrowLeft size={14}/></button><button aria-label="Next suggestions" onClick={()=>scroll(1)}><ArrowRight size={14}/></button></div></div><div className="discovery-rail" ref={rail}>{cards.map(([label,title,body,prompt,img],i)=><button className={`discovery-card discovery-tone-${i}`} key={title} onClick={()=>onAsk(prompt)}><span>{label}</span><h3>{title}</h3><p>{body}</p><img src={`/products/${img}.webp`} alt=""/><span className="discovery-action">{merchant?'Explore with copilot':'Start here'} <ArrowRight size={15}/></span></button>)}{!merchant&&campaign&&<button className="discovery-card discovery-sponsored" onClick={()=>onAsk('Show me breakfast products from the Green Basket campaign')}><span>MERCHANT PROMOTION · LOCAL DEMO</span><h3>{campaign.title}</h3><p>{campaign.body}</p><img src="/products/BRIT-BAKE-001.webp" alt=""/><span className="discovery-action">Explore breakfast <ArrowRight size={15}/></span></button>}</div><small>{merchant?'Specialist roles illustrated in this mock.':'Sample categories · not inferred from your purchase history.'}</small></section>
}
