import type {CSSProperties,ReactNode} from 'react';
import {AudioLines,BarChart3,Check,Clock3,Code2,FileCheck2,Fingerprint,GitBranch,Headphones,Layers3,LockKeyhole,Package,RefreshCw,Search,ShieldCheck,ShoppingBag,SlidersHorizontal,WalletCards} from 'lucide-react';

export const featurePalettes=[
 ['#92c5ff','#162d50','#244d77'],['#c9a3ff','#2d1d49','#54366c'],['#ffb57b','#37251e','#694932'],['#ffdb79','#333019','#5e542c'],
 ['#ff9eb2','#3d1c2a','#6d354b'],['#8ee5de','#123634','#265957'],['#bbc8ff','#222d49','#45577c'],['#ffa6df','#3e2040','#70395e'],
 ['#a5dfca','#1a332c','#325e4c'],['#bce68c','#27361c','#4d6535'],['#d7b5ff','#30213d','#634675'],['#92dcff','#183440','#30637c'],
 ['#ffbbaa','#3d2928','#735047'],['#dfd58b','#353420','#696139'],['#acd4ee','#23333f','#46647b'],['#ffba89','#40251d','#754733'],
 ['#c0c8e7','#292d3f','#4c587c'],['#d6c394','#353022','#6c5b3c'],['#99d5eb','#183241','#315972'],['#e2a9c1','#392330','#744759'],
];
export function featureStyle(index:number):CSSProperties{const [accent,base,glow]=featurePalettes[index];return {'--impact':accent,'--impact-soft':glow,'--feature-base':base,'--feature-glow':glow} as CSSProperties}
const icons=[AudioLines,BarChart3,ShieldCheck,WalletCards,RefreshCw,Clock3,Headphones,ShoppingBag,Fingerprint,FileCheck2,AudioLines,GitBranch,LockKeyhole,Package,FileCheck2,ShieldCheck,Layers3,SlidersHorizontal,Code2,WalletCards];
const names=['Conversation','Merchant catalogue','Manual checkout','Saved permission','Updated checkout','Payment recovery','Customer case','Storefront placement','Evidence explorer','Authoritative bill','Voice session','Specialist routing','Approval binding','Stock revalidation','Sale terms','Execution authority','Durable command','Change proposal','Protocol interfaces','Resolution review'];
function Row({children,value,tone=''}:{children:ReactNode;value:ReactNode;tone?:string}){return <div className={`fui-row ${tone}`}><span>{children}</span><strong>{value}</strong></div>}
function Tag({children}:{children:ReactNode}){return <span className="fui-tag">{children}</span>}
function Amount({label,value}:{label:string;value:string}){return <div className="fui-amount"><span>{label}</span><strong>{value}</strong></div>}
function Trail({items}:{items:string[]}){return <div className="fui-trail">{items.map((item,i)=><div key={item}><i>{i+1}</i><span>{item}</span><Check size={12}/></div>)}</div>}
function Content({index}:{index:number}){
 switch(index){
 case 0:return <><div className="fui-chat">Earphones + snacks. Under ₹800.</div><div className="fui-agent"><AudioLines size={16}/><span>Razor AI · finding a selection</span></div><div className="fui-products"><div><Headphones/><span>Earphones</span><b>Store price</b></div><div><ShoppingBag/><span>Movie snacks</span><b>Paid share</b></div></div><div className="fui-input">Ask about this selection <AudioLines size={16}/></div></>;
 case 1:return <><div className="fui-command-head"><Package size={20}/> Merchant catalogue</div><Row value="useCatalogue">Record source</Row><Row value="Read from store">Products / prices / stock</Row><div className="fui-alert">Analytics and edits include local previews</div><div className="fui-foot">No measured order or revenue figures claimed</div></>;
 case 2:return <><div className="fui-command-head"><WalletCards size={20}/> Manual checkout</div><Trail items={['Authoritative bill','Razorpay test checkout','Backend outcome']}/><div className="fui-foot">Handoff is not capture evidence.</div></>;
 case 3:return <><div className="fui-permission"><WalletCards/><span>Selected essentials</span><Tag>Saved authority</Tag></div><Amount label="Example per-purchase limit" value="Saved limit"/><Row value="Selected products">Scope</Row><Row value="Revocable">Authority</Row><div className="fui-foot">Provider simulation · no live debit</div></>;
 case 4:return <><div className="fui-alert">Merchant offer updated</div><div className="fui-metrics"><Amount label="Previously reviewed" value="Old total"/><Amount label="New total" value="New total"/></div><Row value="Updated discount">Discount change</Row><div className="fui-action">Review & approve updated terms</div></>;
 case 5:return <><div className="fui-radar"><RefreshCw size={32}/><span>Awaiting provider evidence</span></div><Row value="Same operation">Retry identity</Row><Row value={<Tag>Unresolved</Tag>}>Payment status</Row><div className="fui-alert">Please do not pay again</div></>;
 case 6:return <><div className="fui-case"><Tag>LocalStorage preview</Tag><h4>One item arrived damaged</h4><p>Buyer report → Merchant Command</p></div><Trail items={['Issue recorded','Merchant review','Resolution decision']}/><div className="fui-foot">Buyer reports. Merchant reviews.</div></>;
 case 7:return <><div className="fui-email"><span>STOREFRONT PLACEMENT</span><h4>A fresh reason to return.</h4><p>Labelled merchant message · local preview</p></div><Row value="Preview">Shopping conversation</Row><div className="fui-action">Review placement content</div><div className="fui-foot">No email send · no price change</div></>;
 case 8:return <><div className="fui-code"><Fingerprint size={22}/><span>Recompute, don’t assume.</span></div><Trail items={['Canonical content','Bound approval','Execution evidence']}/><Row value={<Tag>Inspect</Tag>}>10-link evidence model</Row></>;
 case 9:return <><div className="fui-code"><FileCheck2 size={20}/> useAuthoritativeBill</div><Trail items={['Create cart','Set requested lines','Read checkout card']}/><div className="fui-foot">The reviewed amounts come from the returned card.</div></>;
 case 10:return <><div className="fui-voice"><AudioLines size={32}/><h4>Razor AI is listening</h4><div>{Array.from({length:25},(_,i)=><i key={i} style={{height:(12+Math.sin(i*.8)**2*36)+'px','--bar':i} as CSSProperties}/>)}</div></div><div className="fui-transcript">“Find everyday essentials…”</div><Row value="Text alternative">Type instead</Row></>;
 case 11:return <><div className="fui-router"><Tag>Razor AI</Tag><div className="fui-route-stem"/><div><span><Search size={18}/>Shopping</span><span><LockKeyhole size={18}/>Checkout</span><span><Headphones size={18}/>Support</span></div></div><div className="fui-foot">Model-backed Shopping when configured<br/>Checkout & Support: deterministic runners</div></>;
 case 12:return <><div className="fui-code"><LockKeyhole size={20}/><span>Approval content binding</span></div><Row value="Bound version">Checkout version</Row><Row value="Bound amount / currency">Approved amount</Row><div className="fui-hash">sha256(canonical content)<br/><b>Version + content + authority</b></div><div className="fui-action">Same content required at admission</div></>;
 case 13:return <><div className="fui-products"><div><Package/><span>Selected item</span><b>Requested units</b></div><div><RefreshCw/><span>Current stock</span><b>Recheck</b></div></div><Row value="Validate">Reservation</Row><Row value="Recompute">Merchant terms</Row><div className="fui-alert">Changed state? Show a new review.</div></>;
 case 14:return <><div className="fui-document"><FileCheck2 size={28}/><h4>Policy-at-Sale Receipt</h4><span>Sale-bound snapshot</span><div/><div/><div/></div><Row value="Preserved">Original sale terms</Row><div className="fui-foot">Later edits do not rewrite this sale.</div></>;
 case 15:return <><div className="fui-grant"><ShieldCheck size={29}/><span>EXECUTION GRANT</span><strong>ONE USE</strong><small>Bound to the admitted operation</small></div><div className="fui-two-states"><Tag>First use → execute</Tag><span>Replay → refuse</span></div></>;
 case 16:return <><div className="fui-command-head"><Layers3 size={20}/> Action Executor</div><Trail items={['Durable command recorded','Worker executes','Outcome recorded']}/><div className="fui-input">Browser closed ≠ operation cancelled</div></>;
 case 17:return <><Tag>Stock proposal · example</Tag><div className="fui-metrics"><Amount label="Before" value="Current stock"/><Amount label="Proposed" value="Proposed stock"/></div><Row value="Source revision">Bound to</Row><div className="fui-action">Merchant reviews exact change</div><div className="fui-foot">No financial authority conferred</div></>;
 case 18:return <><div className="fui-protocols">{['ACP','UCP','MCP','AP2'].map(x=><span key={x}>{x}</span>)}</div><div className="fui-route-stem"/><div className="fui-action"><ShieldCheck size={16}/> Shared authority boundary</div><div className="fui-foot">Adapter support ≠ marketplace listing</div></>;
 default:return <><Tag>Resolution Plan · example</Tag><Row value="Paid share">Paid for affected item</Row><Row value="Ledger value">Already refunded</Row><Amount label="Refundable amount from ledger" value="Paid share"/><div className="fui-action">Review authorised remedy</div><div className="fui-foot">No wallet · no invented credit</div></>;
 }
}
export function FeatureUIArt({index,mini=false}:{index:number;mini?:boolean}){const Icon=icons[index];if(mini)return <div className="feature-ui-mini" style={featureStyle(index)} aria-hidden="true"><Icon size={29}/><span>{String(index+1).padStart(2,'0')}</span><div><i/><i/><i/></div></div>;return <figure className="feature-ui-art" aria-label={`${names[index]}: illustrative interface, not live data`}><div className="fui-window"><header><div><i/><i/><i/></div><span><Icon size={12}/>{names[index]}</span><small>SCHEMATIC</small></header><div className="fui-content"><Content index={index}/></div></div></figure>}
