'use client';
import Link from 'next/link';
import {FeatureUIArt,featureStyle} from './feature-ui-art';
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,ArrowUpRight,AudioLines,Check,Layers3,Pause,Play,ShieldCheck,WalletCards} from 'lucide-react';
import {VoiceWave} from './voice-wave';
const stories=[
 {label:'FOR YOUR CUSTOMERS',icon:AudioLines,title:'A shopping conversation.\nWith somewhere to go.',body:'Say the occasion, budget and what matters. The Shopping Specialist helps turn intent into product choices; the voice gateway brings speech into the journey.',quote:'“Earphones and snacks. Keep it under ₹800.”',steps:['Understand intent','Find available products','Review the exact purchase'],note:'Shopping model-backed when configured · voice availability depends on connection',cta:'Meet your shopping copilot',href:'/shop',color:'blue'},
 {icon:Layers3,"label": "MERCHANT CATALOGUE WORKSPACE", "title": "The merchant’s shelf.\nIn one workspace.", "body": "Merchant Command reads the catalogue through useCatalogue and presents stock and pricing. Its analytics figures and operational edits still include local previews; they are not measured growth outcomes.", "quote": "Read the catalogue. Review the proposed change.", "steps": ["Read catalogue records", "Inspect stock and price", "Review the proposal preview"], "note": "Catalogue read connected · metrics and action previews are not live growth evidence", "cta": "Open the catalogue workspace", "href": "/merchant", "color": "violet"},
 {icon:Layers3,"label": "RAZORPAY MANUAL CHECKOUT", "title": "A real checkout path.\nA server-verified outcome.", "body": "The manual-checkout component uses the authoritative bill and the Razorpay test-checkout path. Its state distinguishes provider handoff from the backend-confirmed result.", "quote": "Opening Razorpay Checkout is not proof of payment capture.", "steps": ["Review the backend bill", "Open provider checkout", "Read the backend outcome"], "note": "Implementation exists · provider configuration and runtime services required", "cta": "Explore checkout", "href": "/shop", "color": "orange"},
 {label:'RESERVE PAY · UAP-STYLE SIMULATION',icon:WalletCards,title:'AI-assisted spending.\nInside your permission.',body:'Selected products, a spending limit and a revocable authority. The backend checks the exact purchase, admits durable work and records the simulated provider outcome.',quote:'“Use my saved permission for these selected essentials.”',steps:['Check products and limits','Validate authority epoch','Execute through simulator'],note:'Server-side provider simulation · NPCI and banks are not connected',cta:'Explore Reserve Pay',href:'/shop#reserve',color:'gold'},
 {label:'WHEN THE OFFER CHANGES',icon:ShieldCheck,title:'New terms.\nA fresh decision.',body:'A merchant changes an applicable offer while the customer is reviewing. Show the new price and breakdown, then ask for fresh approval—even if the total goes down.',quote:'“The offer changed. Here is exactly what is different.”',steps:['Identify the changed terms','Show the itemised difference','Request fresh buyer approval'],note:'Illustrative scenario · financial changes are checked at admission',cta:'Explore approval binding',href:'#innovations',color:'orange'},
 {label:'WHEN THE NETWORK DOESN’T ANSWER',icon:ShieldCheck,title:'Uncertain is a state.\nNot a reason to pay twice.',body:'A request times out after submission. Recover the same operation, preserve the unresolved attempt and let provider evidence establish the outcome.',quote:'“Still checking your payment. Please do not pay again.”',steps:['Recover the same request','Reconcile provider evidence','Confirm the actual outcome'],note:'Architecture illustration · no live payment is running in this slide',cta:'See the recovery principles',href:'#innovations',color:'blue'},
 {icon:Layers3,"label": "BUYER-TO-MERCHANT CASE PREVIEW", "title": "Report the problem.\nLet the merchant review.", "body": "The current support UI records buyer issues in local browser storage and displays those cases in Merchant Command. It demonstrates the escalation experience; it is not yet the backend case workflow.", "quote": "A local support preview—not a completed backend integration.", "steps": ["Capture the issue locally", "Show it in Merchant Command", "Preview merchant review"], "note": "LocalStorage preview · no real refund is executed by this UI", "cta": "View the support preview", "href": "/merchant#support", "color": "violet"},
 {icon:Layers3,label:'STOREFRONT PLACEMENT PREVIEW',title:'A merchant message.\nInside discovery.',body:'Preview a labelled merchant placement in the shopping conversation. It is stored locally and changes neither prices nor Merchant Policy.',quote:'A storefront preview, with no email send.',steps:['Draft a placement','Review its content','Preview it in shopping'],note:'Local browser preview only · email campaign design deferred',cta:'View Merchant Command',href:'/merchant',color:'gold'},
 {label:'THE EVIDENCE BEHIND THE EXPERIENCE',icon:Layers3,title:'Go beyond “success”.\nFollow the record.',body:'Trace the purchase from intent and canonical content to approval, execution authority and provider evidence. Missing evidence is shown as missing, not a green tick.',quote:'“Show me what was approved, executed and confirmed.”',steps:['Recompute content binding','Inspect execution evidence','Read the final recorded state'],note:'Evidence model illustration · use the verifier for an actual purchase',cta:'Inspect the engineering story',href:'#innovations',color:'blue'},
 {icon:Layers3,"label": "AUTHORITATIVE CHECKOUT BILL", "title": "Price the purchase\nfrom the backend.", "body": "useAuthoritativeBill creates the cart, sets its requested lines and asks the backend for a checkout card. That card supplies the reviewed version and amounts instead of a new model-generated bill.", "quote": "The approval card is the review source.", "steps": ["Create cart and set lines", "Request checkout card", "Render the returned bill"], "note": "Source implementation · no live amounts are shown in this presentation", "cta": "Open shopping", "href": "/shop", "color": "blue"},
 {icon:Layers3,"label": "VOICE WITHOUT LOSING CONTROL", "title": "Speak naturally.\nStay in the decision.", "body": "Voice recognition and spoken responses use the gateway path. Typing remains an alternative when voice is unavailable, and spoken content does not bypass trusted financial authority.", "quote": "“Let me explain what I need. Then show me the exact bill.”", "steps": ["Capture spoken intent", "Keep readable conversation context", "Preserve explicit authority"], "note": "Voice gateway implemented · availability is configuration-dependent", "cta": "Meet Razor AI", "href": "/shop", "color": "violet"},
 {icon:Layers3,"label": "SPECIALISTS WITH BOUNDARIES", "title": "Different jobs.\nDeliberate responsibilities.", "body": "Shopping, Checkout and Support have distinct responsibilities. Shopping can use the model bridge; deterministic checkout and support paths preserve the rules around consequential decisions.", "quote": "One interface does not mean one unrestricted agent.", "steps": ["Route the request", "Use scoped capabilities", "Return a grounded result"], "note": "Shopping model-backed when configured · other specialist runners deterministic", "cta": "Explore the architecture", "href": "#innovations", "color": "violet"},
 {icon:Layers3,"label": "EXACT-CONTENT APPROVAL", "title": "Approve the purchase.\nNot an open-ended promise.", "body": "The buyer approval names the checkout version, canonical content hash, amount and currency. The system can test whether execution still corresponds to what was reviewed.", "quote": "A yes to version 3 is not a yes to a different version 4.", "steps": ["Canonicalise the checkout", "Bind approval to its hash", "Check the same content at admission"], "note": "Kernel design · this slide does not verify a live checkout", "cta": "Inspect approval binding", "href": "#innovations", "color": "orange"},
 {icon:Layers3,"label": "REVALIDATION AT THE MONEY BOUNDARY", "title": "The shelf moved.\nThe system checks again.", "body": "Stock, prices, fees and applicable Merchant Policy can change after discovery. Revalidation and reservation checks protect admission from treating an old quote as current merchant state.", "quote": "“Is this exact purchase still valid right now?”", "steps": ["Check reservation", "Revalidate merchant state", "Refuse or request a new review"], "note": "Checks happen server-side · availability is not promised by artwork", "cta": "Explore checkout controls", "href": "#innovations", "color": "gold"},
 {icon:Layers3,"label": "POLICY-AT-SALE RECEIPT", "title": "Terms can change.\nThe sale keeps its evidence.", "body": "Freeze the Merchant Policy terms associated with a sale into a Policy-at-Sale Receipt. Later support and financial decisions can refer to the original sale-bound terms.", "quote": "The merchant’s current terms cannot silently rewrite a completed sale.", "steps": ["Validate receipt inputs", "Bind the frozen snapshot", "Read sale-bound terms later"], "note": "Policy-at-Sale Receipt is distinct from a Provider Receipt", "cta": "Explore sale evidence", "href": "#innovations", "color": "blue"},
 {icon:Layers3,"label": "SINGLE-USE EXECUTION GRANTS", "title": "Permission to execute.\nOnce, within its binding.", "body": "Financial admission creates an Execution Grant bound to the admitted operation. The executor must present the matching authority; a replay is not a fresh permission to move money.", "quote": "A model instruction cannot mint its own financial authority.", "steps": ["Admit a specific operation", "Issue a bound grant", "Consume execution authority once"], "note": "Kernel and executor boundary · not an absolute security guarantee", "cta": "Inspect the engineering", "href": "#innovations", "color": "orange"},
 {icon:Layers3,"label": "DURABLE WORK, NOT A BROWSER TIMER", "title": "Close the tab.\nKeep the work accountable.", "body": "Durable commands preserve admitted work beyond the browser lifecycle. The Action Executor records execution and recovery through the backend rather than relying on a success animation.", "quote": "The UI can disappear. The financial operation still needs an outcome.", "steps": ["Record durable work", "Execute through a worker", "Recover and reconcile"], "note": "Durable backend architecture · runtime services must be available", "cta": "Explore durable execution", "href": "#innovations", "color": "blue"},
 {icon:Layers3,"label": "MERCHANT CONTROL WITHOUT PAYMENT POWER", "title": "Run the business.\nRespect the money boundary.", "body": "The Merchant Action Controller governs typed operational proposals and approvals. It cannot rewrite checkout authority, financial attempts or Execution Grants; remedies use separately authorised financial paths.", "quote": "A stock adjustment is not permission to charge a buyer.", "steps": ["Review a typed proposal", "Check revision and approval", "Invoke the owning domain service"], "note": "Controller implemented · frontend workflows have mixed maturity", "cta": "Open Merchant Command", "href": "/merchant", "color": "violet"},
 {icon:Layers3,"label": "ACP · UCP · MCP · AP2", "title": "Meet the protocols.\nKeep the same controls.", "body": "Version-pinned commerce interfaces, scoped tools and signed interaction evidence support multiple entry points. A protocol adapter does not remove the need for valid buyer authority.", "quote": "Different ways in. The same financial boundary.", "steps": ["Expose compatible interfaces", "Verify scoped interaction context", "Preserve trusted consent"], "note": "Not a live ChatGPT/Gemini marketplace listing or certification", "cta": "Explore protocol boundaries", "href": "#innovations", "color": "gold"},
 {icon:Layers3,"label": "REFUNDS TIED TO WHAT WAS PAID", "title": "Resolve the issue.\nRespect the refundable balance.", "body": "Financial remedies must stay within the paid, refundable amount. A damaged item can require a partial resolution; the buyer raises a case and the merchant reviews the authorised path.", "quote": "No wallet. No invented goodwill balance. No refund beyond the permitted amount.", "steps": ["Identify affected items", "Evaluate a Resolution Plan", "Enforce financial limits"], "note": "Buyer copilot does not approve refunds · merchant resolution governs the next step", "cta": "Explore merchant support", "href": "/merchant#support", "color": "orange"},
];
const featureNames=['Voice shopping','Catalogue workspace','Manual checkout','Reserve / UAP','Changed offers','Payment recovery','Local case preview','Campaign preview','Purchase evidence','Backend bill','Voice gateway','Specialist routing','Approval binding','Revalidation','Sale-bound terms','Execution grants','Durable work','Merchant controls','Open protocols','Refund limits'];
const benefits=['Less searching. A selection shaped by the customer’s intent.','Catalogue records are distinguished from preview metrics.','Provider handoff is distinguished from confirmed payment.','A delegated purchase stays within its saved permission.','Customers can see and approve the changed financial terms.','Uncertainty does not become a reason for a duplicate payment.','A local preview demonstrates the intended case handoff.','Draft review can be explored without pretending emails were sent.','A success claim can be traced back to records.','The review starts from the backend checkout card.','Voice adds convenience without becoming unchecked authority.','Each job receives a scoped path, not unrestricted tools.','The system can test what the buyer actually approved.','The purchase is checked against merchant state at admission.','Original sale terms remain available for later decisions.','Execution authority is specific and single-use.','The operation does not depend on the browser staying open.','Operational approvals cannot bypass financial invariants.','Multiple interfaces can share consistent transaction controls.','Resolutions remain bounded by the money actually paid.'];

const sourcePaths=["packages/commerce-api/src/commerce_api/services/agent_bridge.py", "apps/razorsharp-concept/lib/catalogue.ts", "apps/razorsharp-concept/components/manual-checkout.tsx", "packages/commerce-api/src/commerce_api/routers/reserve.py", "packages/transaction-kernel/src/transaction_kernel/admission.py", "packages/action-executor/src/action_executor/handlers/reserve.py", "apps/razorsharp-concept/components/live-orders.tsx", "apps/razorsharp-concept/app/merchant/page.tsx", "packages/commerce-api/src/commerce_api/services/proof_chain.py", "apps/razorsharp-concept/lib/authoritative-bill.ts", "apps/razorsharp-concept/components/voice-session.tsx", "packages/commerce-api/src/commerce_api/services/agent_bridge.py", "packages/transaction-kernel/src/transaction_kernel/approvals.py", "packages/transaction-kernel/src/transaction_kernel/reservations.py", "packages/transaction-kernel/src/transaction_kernel/receipts.py", "packages/transaction-kernel/src/transaction_kernel/grants.py", "packages/action-executor/src/action_executor/loop.py", "packages/merchant-controller/src/merchant_controller/actions.py", "packages/commerce-api/src/commerce_api/routers/protocols.py", "packages/transaction-kernel/src/transaction_kernel/refunds.py"];
export function ImpactDeck(){
 const [index,setIndex]=useState(0),[paused,setPaused]=useState(false),[keyboardFocus,setKeyboardFocus]=useState(false),[visible,setVisible]=useState(false),[motion,setMotion]=useState(false),[showIndex,setShowIndex]=useState(false);
 const root=useRef<HTMLElement>(null),start=useRef<number|null>(null);
 useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)');const sync=()=>setMotion(!media.matches&&document.documentElement.dataset.motion!=='paused'&&!document.hidden);sync();media.addEventListener('change',sync);window.addEventListener('razorsharp:motion',sync);document.addEventListener('visibilitychange',sync);const observer=new IntersectionObserver(([entry])=>setVisible(entry.isIntersecting),{threshold:.25});if(root.current)observer.observe(root.current);return()=>{observer.disconnect();media.removeEventListener('change',sync);window.removeEventListener('razorsharp:motion',sync);document.removeEventListener('visibilitychange',sync)}},[]);

 useEffect(()=>{if(paused||keyboardFocus||showIndex||!visible||!motion)return;const timer=setTimeout(()=>setIndex(i=>(i+1)%stories.length),6500);return()=>clearTimeout(timer)},[index,paused,keyboardFocus,showIndex,visible,motion]);
 const go=(next:number)=>{setIndex((next+stories.length)%stories.length)};
 const story=stories[index],Icon=story.icon;
 return <section className="impact-deck" id="why-razorsharp" ref={root} aria-label="How RazorSharp helps" aria-roledescription="carousel" onFocusCapture={e=>{if(e.target instanceof HTMLElement&&e.target.matches(':focus-visible'))setKeyboardFocus(true)}} onBlurCapture={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node|null))setKeyboardFocus(false)}}>
  <div className="impact-intro"><span>RAZORSHARP PLATFORM / POWERED BY RAZOR AI</span><h2>Inside RazorSharp.<br/><em>What is actually built.</em></h2><p>A voice-first shopping experience. A merchant action workspace. A transaction architecture built to make consequential decisions inspectable.</p></div><div className="impact-deck-toolbar"><span><Layers3 size={15}/> IMPLEMENTATION WALKTHROUGH</span><button aria-expanded={showIndex} aria-controls="impact-feature-index" onClick={()=>setShowIndex(v=>!v)}>{showIndex?'Close feature index':'Browse implementation areas'}<ArrowRight size={16}/></button></div>{showIndex&&<nav id="impact-feature-index" className="impact-feature-index" aria-label="All platform features">{featureNames.map((name,i)=><button key={name} aria-pressed={index===i} onClick={()=>{go(i);setShowIndex(false)}}><span>{String(i+1).padStart(2,'0')}</span>{name}</button>)}</nav>}
  <div className="impact-stage" onTouchStart={e=>{start.current=e.touches[0].clientX}} onTouchEnd={e=>{if(start.current!==null){const delta=e.changedTouches[0].clientX-start.current;if(Math.abs(delta)>55)go(index+(delta<0?1:-1));start.current=null}}}>
   <div className="impact-backplate impact-backplate-two" aria-hidden="true"/><div className="impact-backplate" aria-hidden="true"/>
   <article className={`impact-card impact-cinematic impact-${story.color}`} style={featureStyle(index)} key={index}><div className="impact-copy"><span className="impact-feature-no">AREA {String(index+1).padStart(2,'0')} / 20</span><div className="impact-kicker"><Icon size={20}/>{story.label}</div><h3>{story.title}</h3><p>{story.body}</p><div className="impact-benefit"><span>WHY IT MATTERS</span><strong>{benefits[index]}</strong></div><Link href={story.href}>{story.cta}<ArrowUpRight size={18}/></Link><small>{story.note}</small><details className="impact-source-detail"><summary>Implementation reference</summary><code>{sourcePaths[index]}</code><p>Source reference, not a test result. Inspect in the local repository; frontend files may still be uncommitted.</p></details></div><div className="impact-visual"><FeatureUIArt index={index}/><div className="impact-quote"><span><AudioLines size={15}/> CONVERSATION TO ACTION</span><blockquote>{story.quote}</blockquote>{index===0?<VoiceWave mode="listening"/>:<div className="impact-flow-line" aria-hidden="true"><i/><i/><i/></div>}</div><ol>{story.steps.map((step,i)=><li key={step} style={{'--step':i} as React.CSSProperties}><span>{i===2?<Check size={15}/>:i+1}</span><strong>{step}</strong><ArrowRight size={14}/></li>)}</ol><span className="impact-illustration">Code-based explanation · not a screenshot or live result</span></div></article>
  </div>
  <output className="impact-autoplay-status"><i data-running={!paused&&!keyboardFocus&&!showIndex&&motion}/>{paused?'Autoplay paused':!motion?'Motion paused':keyboardFocus||showIndex?'Paused while you explore':'Autoplay · next story every 6.5 seconds'}</output><div className="impact-controls"><span>{String(index+1).padStart(2,'0')} <i>/ {String(stories.length).padStart(2,'0')}</i></span><div className="impact-pagination"><span>{featureNames[index]}</span><div><i style={{width:`${(index+1)/stories.length*100}%`}}/></div></div><button aria-label="Previous story" onClick={()=>go(index-1)}><ArrowLeft size={17}/></button><button aria-label={paused?'Play stories':'Pause stories'} onClick={()=>{setPaused(p=>!p);setKeyboardFocus(false)}}>{paused?<Play size={15}/>:<Pause size={15}/>}</button><button aria-label="Next story" onClick={()=>go(index+1)}><ArrowRight size={17}/></button></div>
  <nav className="impact-filmstrip" aria-label="Feature slides">{featureNames.map((name,i)=><button key={name} aria-pressed={index===i} onClick={()=>go(i)}><FeatureUIArt index={i} mini/><span><i>{String(i+1).padStart(2,'0')}</i>{name}</span></button>)}</nav>
  <section className="impact-track" id="track-one" aria-labelledby="track-one-title"><div className="impact-track-heading"><span>RAZORPAY BUILDATHON / TRACK 1 THEME</span><h3 id="track-one-title">AI growth meets<br/><em>agentic commerce.</em></h3><p>RazorSharp connects the merchant’s next action to the customer’s next purchase—with explicit controls at the point where money moves.</p></div><div className="impact-track-grid">{[
 ['01','Help merchants grow','Merchant Command brings catalogue context, business questions and campaign proposals into one reviewable workspace.','Connected catalogue · analytics and campaigns include previews'],
 ['02','Turn intent into commerce','Razor AI combines voice interaction and a Shopping Specialist with product discovery and exact-checkout review.','Shopping model bridge and voice gateway implemented; configuration required'],
 ['03','Make agentic spending accountable','Reserve Pay explores selected-product, bounded, revocable authority with Kernel admission and durable execution.','UAP-style server simulation · no live NPCI or bank connection'],
 ['04','Connect through commerce protocols','ACP/UCP interfaces and MCP/AP2 capabilities preserve authority boundaries across different entry points.','Protocol implementations · not marketplace availability or certification'],
 ['05','Build beyond the happy path','Content-bound approval, idempotency, single-use grants and reconciliation address changing terms, retries and uncertain outcomes.','Backend controls · validate runtime behaviour with the test suites'],
 ['06','Make the engineering inspectable','The evidence model connects intent, approval, execution and provider outcome. Missing evidence remains explicit.','Verifier implemented · homepage visuals are illustrations'],
 ].map(([n,title,body,status])=><article key={n}><span>{n}</span><h4>{title}</h4><p>{body}</p><small>{status}</small></article>)}</div><footer><p>Alignment with the AI Growth & Agentic Commerce theme, not a claim of endorsement or full scoring-rubric compliance.</p></footer></section>
  <div className="impact-distinct"><div><Layers3 size={24}/><span>BUILT TO EARN A CLOSER LOOK</span><h3>Product depth.<br/>Engineering substance.</h3></div><p>Razor AI connects voice interaction and specialist responsibilities with two workspaces. RazorSharp surrounds that experience with exact-order approval, revocable authority, durable execution and inspectable evidence.<br/><strong>Connected paths, backend controls and frontend previews are different things. The source references show what each claim is based on.</strong></p><Link href="#highlights">See how it fits together <ArrowRight size={17}/></Link></div>
 </section>;
}
