'use client';
import {useEffect,useState} from 'react';
import {ArrowUpRight,Package,ShoppingBag,Headphones,ShieldCheck,RefreshCw,ArrowRight,Sparkles} from 'lucide-react';
import {merchantCall} from './live-merchant';
import {useCatalogue} from '@/lib/catalogue';
import {formatMinor,LOW_STOCK_UNITS} from '@/lib/merchant-facts';
import type {OrdersPage} from '@/lib/commerce';
import type {MerchantAction} from './merchant-action-card';

type Insights={days:number;observed_at:string;definition:string;totals:{currency:string;orders:number;sales_minor:number}[]};
type Cases={cases:{case_id:string;order_reference:string;reason:string;status:string}[];may_have_more?:boolean};
type Actions={actions:MerchantAction[];may_have_more?:boolean};
type Snapshot={insights:Insights|null;orders:OrdersPage|null;cases:Cases|null;actions:Actions|null;errors:string[]};
const empty:Snapshot={insights:null,orders:null,cases:null,actions:null,errors:[]};
const QUICK_ASKS=['Summarise my priorities for today','Which products need restocking?','What is awaiting my approval?'] as const;
export function MerchantDashboard({revision,onNavigate,onAsk}:{revision:number;onNavigate:(view:string,orderId?:string)=>void;onAsk?:(question:string)=>void}){
 const [days,setDays]=useState(7),[refresh,setRefresh]=useState(0),[busy,setBusy]=useState(true),[data,setData]=useState<Snapshot>(empty);
 const catalogue=useCatalogue();
 const identity=`${days}:${revision}:${refresh}`;const [previous,setPrevious]=useState(identity);if(previous!==identity){setPrevious(identity);setBusy(true);setData(empty)}
 useEffect(()=>{let live=true;
 const paths=[`merchant/insights?days=${days}`,'orders?limit=5','support/cases?status=OPEN&limit=5&offset=0','merchant/actions?state=AWAITING_APPROVAL&limit=5&offset=0'];
 void Promise.allSettled(paths.map(path=>merchantCall(path))).then(results=>{if(!live)return;const value=(i:number)=>results[i].status==='fulfilled'?results[i].value:null;setData({insights:value(0) as unknown as Insights|null,orders:value(1) as unknown as OrdersPage|null,cases:value(2) as unknown as Cases|null,actions:value(3) as unknown as Actions|null,errors:results.flatMap((r,i)=>r.status==='rejected'?[`${['Sales','Orders','Support','Approvals'][i]}: ${r.reason instanceof Error?r.reason.message:'Could not load records'}`]:[])});setBusy(false)});
 return()=>{live=false};
 },[days,revision,refresh]);
 const low=catalogue.products.filter(p=>p.stock<=LOW_STOCK_UNITS).sort((a,b)=>a.stock-b.stock);
 const count=data.insights?.totals.reduce((sum,r)=>sum+r.orders,0);
  return <div className="merchant-dashboard" aria-busy={busy}>
   <header className="dashboard-heading"><div><span className="workspace-kicker">MERCHANT OVERVIEW</span><h1>Your business, at a glance.</h1><p>Recorded performance. Clear priorities. Your next action.</p></div><div className="dashboard-toolbar"><label><span className="sr-only">Sales period</span><select value={days} onChange={e=>setDays(Number(e.target.value))}><option value={7}>Last 7 days</option><option value={30}>Last 30 days</option><option value={90}>Last 90 days</option></select></label><button className="workspace-icon-button" aria-label="Refresh dashboard" disabled={busy} onClick={()=>setRefresh(v=>v+1)}><RefreshCw size={17}/></button></div></header>
   {onAsk&&<><button type="button" className="ai-command-strip" onClick={()=>onAsk('Give me a 30-second brief: sales, inventory risks, approvals and support cases.')} aria-label="Ask Copilot for a business brief"><span className="ai-command-icon"><Sparkles size={18}/></span><span><strong>Ask Copilot anything about your business</strong><small>Try “Which products need restocking?” · “Draft a price change” · “Summarise open cases”</small></span><ArrowUpRight size={16}/></button><div className="ai-quick-asks" aria-label="Suggested Copilot questions">{QUICK_ASKS.map(q=><button key={q} type="button" onClick={()=>onAsk(q)}><Sparkles size={13}/>{q}</button>)}</div></>}
  {data.errors.length>0&&<div className="workspace-alert" role="alert"><strong>Some records could not be loaded.</strong>{data.errors.map(e=><p key={e}>{e}</p>)}<button onClick={()=>setRefresh(v=>v+1)}>Retry dashboard</button></div>}
  <div className="dashboard-metrics">
   <section className="dashboard-metric"><span className="metric-icon metric-blue"><ShoppingBag size={19}/></span><span>Confirmed order value</span><div className="dashboard-metric-value">{data.insights?(data.insights.totals.length?data.insights.totals.map(r=><strong key={r.currency}>{formatMinor(r.sales_minor,r.currency)}</strong>):<strong>No sales</strong>):<strong>—</strong>}</div><small>Before refunds · {days} days</small></section>
   <button className="dashboard-metric" onClick={()=>onNavigate('orders')}><span className="metric-icon metric-violet"><Package size={19}/></span><span>Confirmed orders</span><strong>{count??'—'}</strong><small>View orders <ArrowUpRight size={13}/></small></button>
   <button className="dashboard-metric" onClick={()=>onNavigate('support')}><span className="metric-icon metric-amber"><Headphones size={19}/></span><span>Open support cases</span><strong>{data.cases?`${data.cases.cases.length}${data.cases.may_have_more?'+':''}`:'—'}</strong><small>Open Support Desk <ArrowUpRight size={13}/></small></button>
   <button className="dashboard-metric" onClick={()=>onNavigate('activity')}><span className="metric-icon metric-mint"><ShieldCheck size={19}/></span><span>Awaiting approval</span><strong>{data.actions?`${data.actions.actions.length}${data.actions.may_have_more?'+':''}`:'—'}</strong><small>Review action queue <ArrowUpRight size={13}/></small></button>
  </div>
  <div className="dashboard-columns"><section className="dashboard-panel"><header><div><h2>Recent orders</h2><p>Latest recorded purchases</p></div><button onClick={()=>onNavigate('orders')}>All orders <ArrowRight size={14}/></button></header>
   {!data.orders?<p className="dashboard-empty">{busy?'Reading orders…':'Orders unavailable. Retry to reconnect.'}</p>:!data.orders.orders.length?<p className="dashboard-empty">Your first confirmed order will appear here.</p>:<div className="dashboard-order-list">{data.orders.orders.map(order=><button key={order.order_id} onClick={()=>onNavigate('orders',order.order_id)}><span className="dashboard-order-mark"><ShoppingBag size={18}/></span><span><strong>{order.reference}</strong><small>{new Date(order.created_at).toLocaleDateString('en-IN',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})}</small></span><span><strong>{formatMinor(order.amount_minor,order.currency)}</strong><small className="workspace-status">{order.state.replaceAll('_',' ').toLowerCase()}</small></span><ArrowUpRight size={15}/></button>)}</div>}
  </section><section className="dashboard-panel"><header><div><h2>Inventory attention</h2><p>Storefront items · {LOW_STOCK_UNITS} units or fewer</p></div><button onClick={()=>onNavigate('catalogue')} aria-label="Open catalogue and inventory"><ArrowUpRight size={17}/></button></header>
   {catalogue.error?<p className="workspace-alert">Inventory unavailable: {catalogue.error}</p>:catalogue.loading?<p className="dashboard-empty">Reading inventory…</p>:!low.length?<p className="dashboard-empty">No low-stock items in the current storefront catalogue.</p>:<><div className="dashboard-stock-list">{low.slice(0,5).map(p=><button key={p.id} onClick={()=>onNavigate('catalogue')}><Package size={17}/><span>{p.name}</span><strong data-empty={p.stock<=0}>{p.stock<=0?'Out of stock':`${p.stock} left`}</strong></button>)}</div><button className="dashboard-text-action" onClick={()=>onNavigate('catalogue')}>Inspect all {low.length} stock signals <ArrowRight size={14}/></button></>}
  </section></div>
  <div className="dashboard-columns"><section className="dashboard-panel"><header><div><h2>Approval inbox</h2><p>Changes wait for your decision</p></div><button onClick={()=>onNavigate('activity')}>Review queue <ArrowRight size={14}/></button></header>{!data.actions?<p className="dashboard-empty">{busy?'Reading approvals…':'Approvals unavailable.'}</p>:!data.actions.actions.length?<p className="dashboard-empty">No actions awaiting approval.</p>:data.actions.actions.map(a=><button className="dashboard-action-row" key={a.action_id} onClick={()=>onNavigate('activity')}><ShieldCheck size={18}/><span><strong>{a.target}</strong><small>{a.kind.replaceAll('_',' ')}</small></span><ArrowUpRight size={15}/></button>)}</section>
  <section className="dashboard-panel dashboard-shortcuts"><header><div><h2>Run your store</h2><p>Go straight to the tools you need</p></div></header>{[['catalogue','Manage catalogue','Prices, stock and product availability',Package],['policy','Merchant Policy','Published sale terms and changes',ShieldCheck],['support','Customer Support Desk','Respond to your customers',Headphones]] .map(([view,title,description,Icon])=>{const Glyph=Icon as typeof Package;return <button key={String(view)} onClick={()=>onNavigate(String(view))}><Glyph size={19}/><span><strong>{String(title)}</strong><small>{String(description)}</small></span><ArrowUpRight size={15}/></button>})}</section></div>
  <footer className="dashboard-footnote">{data.insights?.definition??'Sales are shown from recorded orders, separately for each currency.'}{data.insights?.observed_at&&<span>Updated {new Date(data.insights.observed_at).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'})}</span>}</footer>
 </div>;
}
