'use client';
import type {ReactNode} from 'react';
import {WalletCards,ShieldCheck,Landmark,CreditCard,Check} from 'lucide-react';
import {money} from '@/lib/demo';
import './payment-journey.css';

export type JourneyQuote={lines:{sku:string;name:string;quantity:number;unit_price_minor:number;subtotal_minor:number}[];items_subtotal_minor:number;items_tax_minor:number;delivery_tax_minor:number;delivery_fee_minor:number;discount_minor:number};
export type JourneyPhase='processing'|'verifying'|'attention'|'failed'|'completed';
export function PaymentBill({quote,amount,method}:{quote?:JourneyQuote|null;amount:number;method:'reserve'|'razorpay'}){
 return <aside className="journey-bill" aria-label="Exact purchase bill"><span className="journey-eyebrow">YOUR EXACT BILL</span><h3>{method==='reserve'?'Within your permission.':'Your approved purchase.'}</h3><strong className="journey-bill-total">{money(amount)}</strong>{quote?<><ul>{quote.lines.map(line=><li key={line.sku}><strong>{line.name}</strong><span>{line.quantity} × {money(line.unit_price_minor)}<b>{money(line.subtotal_minor)}</b></span></li>)}</ul><dl>{[['Items',quote.items_subtotal_minor],['Tax',quote.items_tax_minor+quote.delivery_tax_minor],['Delivery',quote.delivery_fee_minor],['Merchant offer',-quote.discount_minor],['Total',amount]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{money(Number(value))}</dd></div>)}</dl></>:<output>Reading the recorded bill…</output>}<small>{method==='reserve'?'Reserve Pay · simulated spending capacity':'Razorpay Checkout · your approved bill'}</small></aside>;
}
export function PaymentKernelFlow({method,phase,admitted=false}:{method:'reserve'|'razorpay';phase:JourneyPhase;admitted?:boolean}){
 const reserve=method==='reserve',done=phase==='completed',blocked=phase==='attention'||phase==='failed';
 return <aside className="journey-kernel" data-method={method} data-phase={phase} data-admitted={admitted||done} aria-label={`${reserve?'Reserve Pay':'Razorpay'} Kernel flow`}><span className="journey-eyebrow">TRANSACTION TRUST KERNEL</span><h3>{reserve?'Permission to payment.':'Approval to capture.'}</h3><svg className="journey-kernel-drawing" viewBox="0 0 220 405" fill="none" aria-hidden="true"><path className="journey-wire" d="M110 100V166M110 239V305"/><path className="journey-wire-active" d="M110 100V166M110 239V305"/><circle className="journey-packet" cx="110" cy="105" r="4"/><g className="journey-source"><rect x="76" y="30" width="68" height="68" rx="20"/>{reserve?<WalletCards x="92" y="46" width="36" height="36"/>:<CreditCard x="92" y="46" width="36" height="36"/>}</g><g className="journey-guard"><rect className="journey-guard-orbit" x="65" y="155" width="90" height="90" rx="28"/><rect x="76" y="166" width="68" height="68" rx="20"/><ShieldCheck x="92" y="182" width="36" height="36"/></g><g className="journey-destination"><rect x="76" y="303" width="68" height="68" rx="20"/><Landmark x="92" y="319" width="36" height="36"/>{done&&<g className="journey-capture-check"><circle cx="143" cy="307" r="12"/><Check x="135" y="299" width="16" height="16"/></g>}</g></svg><ol className="journey-node-labels"><li><strong>{reserve?'Reserved capacity':'Exact checkout approval'}</strong><span>{reserve?'Bound to your saved permission':'Your approval stays with this bill'}</span></li><li><strong>Kernel validation</strong><span>{admitted||done?'Execution attempt recorded':'Waiting for admission'}</span></li><li><strong>{reserve?'Merchant · simulated provider':'Razorpay capture evidence'}</strong><span>{done?'Order confirmed':blocked?'Outcome needs attention':'Awaiting verified outcome'}</span></li></ol><p>{done?'Capture evidence recorded. Your order is confirmed.':phase==='attention'?'Outcome unconfirmed. Do not pay again.':phase==='failed'?'Payment not completed. Use recovery controls.':'Animation follows the payment; it never confirms it.'}</p></aside>;
}
export function PaymentJourney({quote,amount,method,phase,admitted,children}:{quote?:JourneyQuote|null;amount:number;method:'reserve'|'razorpay';phase:JourneyPhase;admitted?:boolean;children:ReactNode}){
 if(phase==='completed')return <div className="payment-confirmed-surface">{children}</div>;
 return <div className="payment-journey" data-method={method}><PaymentBill quote={quote} amount={amount} method={method}/><div className="journey-centre">{children}</div><PaymentKernelFlow method={method} phase={phase} admitted={admitted}/></div>;
}
