'use client';
import { ReserveMotif } from './reserve-motif';
import { useEffect,useRef,useState } from 'react';
import { Check,Clock3,ArrowRight,LockKeyhole } from 'lucide-react';
import { money,type Product } from '@/lib/demo';
import { commerce,permissions,reserveReview,type Permission,type ReviewCard,type PaymentStatus } from '@/lib/reserve-api';
export type ReserveConfirmation={orderId:string;attemptId:string;card:ReviewCard;remainingMinor:number|null};
type Pending={card:ReviewCard;authority:Permission;key:string;attemptId?:string};
const storageKey='rs-reserve-pending';
function savePending(value:Pending|null){try{if(value)sessionStorage.setItem(storageKey,JSON.stringify(value));else sessionStorage.removeItem(storageKey)}catch{/* Backend recovery remains authoritative if browser storage is unavailable. */}}
// `reviewed` is the approval card the review screen already built. When it is present this
// component must NOT create another: a second `POST /carts/{id}/checkout` is a second
// checkout holding a second stock reservation for one purchase, and the buyer would be
// paying against a card they were never shown. It is only absent on the legacy path where
// Reserve was entered without a priced review.
export function ReserveCheckout({total,lines,basket,onConfirmed,onBack,onGuidance,commitRequest=0,onReviewState,onFreshReview,reviewed}:{total:number;lines:Product[];basket:Record<string,number>;onConfirmed:(result:ReserveConfirmation)=>void;onBack:()=>void;onGuidance:(message:string)=>void;commitRequest?:number;onReviewState?:(card:ReviewCard|null)=>void;reviewed?:ReviewCard|null;onFreshReview:(checkoutId:string)=>Promise<void>}){
 const [card,setCard]=useState<ReviewCard|null>(null),[authority,setAuthority]=useState<Permission|null>(null),[options,setOptions]=useState<Permission[]>([]),[status,setStatus]=useState<PaymentStatus|null>(null),[error,setError]=useState(''),[expired,setExpired]=useState(!!reviewed?.reservation&&Date.parse(reviewed.reservation.expires_at)<=Date.now()),[busy,setBusy]=useState(true),[pending,setPending]=useState<Pending|null>(null);
 const guide=useRef(onGuidance);guide.current=onGuidance;const confirmed=useRef(false);const init=useRef<Promise<void>|null>(null);const paying=useRef(false);
 useEffect(()=>{if(!init.current)init.current=(async()=>{try{
  let stored:string|null=null;try{stored=sessionStorage.getItem(storageKey)}catch{}if(stored){const p=JSON.parse(stored) as Pending;if(!p.card?.checkout_id||!p.authority?.authority_id||!p.key)throw new Error('Saved payment recovery data is invalid. Check your orders before paying again.');if(!reviewed||p.card.checkout_id!==reviewed.checkout_id||p.card.content_hash!==reviewed.content_hash)throw new Error('A different purchase is pending. Check your existing order before starting another payment.');setPending(p);setCard(p.card);setAuthority(p.authority);guide.current('Restoring your pending Reserve purchase. I will check the backend before allowing another payment.');return}
  const a=await permissions();const available=a.authorities.filter(a=>a.status==='ACTIVE');setOptions(available);setAuthority(available[0]||null);
  if(reviewed?.reservation&&Date.parse(reviewed.reservation.expires_at)<=Date.now())setExpired(true);
  if(!available.length){setError('Set up a saved Reserve permission first.');return}
  const c=reviewed??await reserveReview(lines,basket);setCard(c);guide.current(`Review the backend bill of ${money(c.amount_minor)}. Paying checks it against your saved permission.`);
 }catch(e){setError((e as Error).message)}finally{setBusy(false)}})()},[]);
 useEffect(()=>{if(!pending?.attemptId)return;let cancelled=false;let polling=false;const poll=async()=>{if(polling)return;polling=true;try{const s=await commerce<PaymentStatus>(`reserve/payments/${pending.attemptId}`);if(cancelled)return;setStatus(s);
 if(s.status==='CAPTURED'&&s.order_id&&!confirmed.current){confirmed.current=true;savePending(null);const saved=await permissions().catch(()=>null);if(cancelled)return;onConfirmed({orderId:s.order_id,attemptId:s.attempt_id,card:pending.card,remainingMinor:saved?.authorities.find(a=>a.authority_id===pending.authority.authority_id)?.available_minor??null});guide.current('The backend has confirmed the simulated payment and created your order. What would you like next?')}
 else if(s.status==='FAILED'){savePending(null);guide.current('The simulated payment failed. Its reserved capacity has been released. You can return to payment options.')}
 }catch(e){if(!cancelled)setError((e as Error).message)}finally{polling=false}};void poll();const timer=setInterval(poll,1500);return()=>{cancelled=true;clearInterval(timer)}},[pending?.attemptId]);
 async function submit(){if(paying.current||!card||!authority||(!pending&&(outside||over||expired)))return;paying.current=true;setBusy(true);setError('');
 const p=pending||{card,authority,key:crypto.randomUUID()};setPending(p);savePending(p);
 try{const result=await commerce<{allowed:boolean;code:string;explanation:string;attempt_id?:string;approval_card?:ReviewCard}>(`reserve/checkouts/${p.card.checkout_id}/versions/${p.card.version}/pay`,'POST',{authority_id:p.authority.authority_id,authority_epoch:p.authority.epoch,content_hash:p.card.content_hash,amount_minor:p.card.amount_minor,currency:p.card.currency},p.key);
 if(result.attempt_id&&(result.allowed||result.code==='DUPLICATE_OPERATION')){const next={...p,attemptId:result.attempt_id};setPending(next);savePending(next);guide.current('Permission checked. Your simulated debit is queued. I am waiting for confirmed backend evidence.');}
 else {setPending(null);savePending(null);if(result.approval_card)setCard(result.approval_card);setExpired(result.code==='RESERVATION_EXPIRED');setError(result.code==='RESERVATION_EXPIRED'?'Your stock hold has ended. The shop is no longer holding these items for this checkout. Your Reserve Pay permission has not expired. Refresh stock and review the latest prices before paying.':result.code==='REAPPROVAL_REQUIRED'?'The merchant changed this purchase. Review the updated bill and approve it again.':`${result.code}: ${result.explanation}`)}
 }catch(e){setError(`${(e as Error).message}. Outcome not confirmed. Retry this same request to recover; do not start another payment.`)}finally{paying.current=false;setBusy(false)}}
 const mismatch=!!card&&card.amount_minor!==total;const scope=authority?.allowed_skus??null;const outside=!!scope&&!!card&&card.quote.lines.some(l=>!scope.includes(l.sku));const over=!!card&&!!authority&&(card.amount_minor>authority.per_purchase_limit_minor||card.amount_minor>authority.available_minor);
 const submitRef=useRef(submit);submitRef.current=submit;
 useEffect(()=>{if(commitRequest>0)void submitRef.current()},[commitRequest]);
 useEffect(()=>{onReviewState?.(!pending&&!busy&&card&&authority&&!outside&&!over&&!expired?card:null)},[card,pending,busy,authority,outside,over,expired]);

 if(busy&&!card)return <section className="reserve-entry-loader" aria-label="Starting Reserve Pay"><div className="reserve-entry-brand">razorsharp<span>ai</span></div><span className="reserve-entry-tag">AI-ASSISTED PAYMENT</span><div className="reserve-entry-symbol" aria-hidden="true"><svg viewBox="0 0 120 120" fill="none"><circle className="reserve-entry-track" cx="60" cy="60" r="48"/><circle className="reserve-entry-saffron" cx="60" cy="60" r="48"/><circle className="reserve-entry-orange" cx="60" cy="60" r="38"/></svg><LockKeyhole size={31}/></div><h2>Preparing your<br/><em>exact purchase</em></h2><p role="status">Reading saved permission and the backend bill…</p><span className="reserve-entry-mock">SERVER-SIDE SIMULATION · NO REAL PAYMENT</span></section>;
 return <div className="reserve-inline-checkout"><section className="reserve-checkout-summary"><ReserveMotif/><div className="reserve-inline-kicker">RESERVE PAY <span>SIMULATED PROVIDER</span></div><h2>Your request.<br/><em>Within your permission.</em></h2><div className="reserve-inline-amount">{money(card?.amount_minor??total)}<span>exact backend bill</span></div>{card?.quote.lines.map(l=><div className="mini-product" key={l.sku}><div><strong>{l.name}</strong><p>{l.quantity} × {money(l.unit_price_minor)}</p></div></div>)}{card&&<div className="review-breakdown"><div><span>Items</span><strong>{money(card.quote.items_subtotal_minor)}</strong></div><div><span>Tax</span><strong>{money(card.quote.items_tax_minor+card.quote.delivery_tax_minor)}</strong></div><div><span>Delivery</span><strong>{money(card.quote.delivery_fee_minor)}</strong></div><div><span>Merchant offer</span><strong>−{money(card.quote.discount_minor)}</strong></div><div><span>Total</span><strong>{money(card.amount_minor)}</strong></div></div>}<small>NPCI UAP and your bank are not connected. This executes through the backend simulator.</small></section>
 <section className="reserve-checkout-progress">{expired&&!error&&<div className="review-changed" role="alert"><strong>Your stock hold has ended</strong><p>The shop is no longer holding these items for this checkout. Your Reserve Pay permission has not expired. Refresh stock and review the latest availability and prices before paying.</p></div>}{error&&<div className="review-changed" role="alert">{error}</div>}{mismatch&&!pending&&<p className="review-changed">The backend bill differs from the earlier visual preview. Review these current prices and fees before paying.</p>}{!pending&&options.length>1&&<label className="form-field">Use saved permission<select value={authority?.authority_id} onChange={e=>setAuthority(options.find(a=>a.authority_id===e.target.value)||null)}>{options.map(a=><option value={a.authority_id} key={a.authority_id}>{money(a.per_purchase_limit_minor)} per purchase · {money(a.available_minor)} available</option>)}</select></label>}{authority&&<div className="reserve-permission-mini"><LockKeyhole/><div><strong>{money(authority.per_purchase_limit_minor)} per purchase</strong><p>{money(authority.available_minor)} available · {authority.allowed_skus===null?'every product in this shop':'only your selected products'}</p></div></div>}
 {authority&&card&&<div className="review-breakdown" aria-label="Reserve Pay balance"><div><span>Total authorised capacity</span><strong>{money(authority.capacity_minor)}</strong></div><div><span>Available Reserve balance{pending?' before this payment':''}</span><strong>{money(authority.available_minor)}</strong></div><div><span>This bill</span><strong>{money(card.amount_minor)}</strong></div><div className="review-final"><span>{pending?'Expected remaining after confirmation':'Remaining if this payment succeeds'}</span><strong>{authority.available_minor>=card.amount_minor?money(authority.available_minor-card.amount_minor):'Insufficient capacity'}</strong></div><small>Simulated spending capacity, not a bank or wallet balance. The backend checks the current balance when payment is submitted.</small></div>}
 {pending?.attemptId?<><div className="reserve-inline-steps">{['Exact bill approved','Permission checked and capacity allocated','Durable debit queued','Provider outcome'].map((label,i)=><div className={i<3?'done':'current'} key={label}><span>{i<3?<Check size={14}/>:<Clock3 size={14}/>}</span><div><strong>{label}</strong><p>{i===3?(status?.status||'Waiting for executor'):'Recorded by backend'}</p></div></div>)}</div><p role="status">{status?.status==='FAILED'?'Payment failed; no order placed.':'Please do not pay again. Closing this view does not cancel an admitted debit.'}</p>{status?.status==='FAILED'&&<button className="secondary" onClick={onBack}>Return to payment options</button>}</>:<>{outside&&<p role="alert">This bill includes a product outside your permission's selected products.</p>}{over&&<p role="alert">This bill exceeds the saved per-purchase limit or available capacity.</p>}<button className="primary" disabled={busy||!card||!authority||(!pending&&(outside||over||expired))} onClick={submit}>{pending?'Recover the same payment request':`Pay ${money(card?.amount_minor??total)} with Reserve Pay`} <ArrowRight size={16}/></button>{expired&&card&&<button className="secondary" disabled={busy} onClick={()=>{setBusy(true);void onFreshReview(card.checkout_id).catch(e=>{setError(e.message);setBusy(false)})}}>Refresh stock and review again</button>}{!pending&&<button className="secondary" onClick={onBack}>Back to review</button>}</>}
 </section></div>
}
