'use client';
import Image from 'next/image';
import {CampaignArtwork} from './campaign-artwork';
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,Pause,Play} from 'lucide-react';
const slides=[
 {tag:'QUICK COMMERCE, IN CONVERSATION',title:'Your day needs more\nthan groceries.',body:'From a forgotten charger to your everyday essentials. Tell your copilot what you need; availability is checked with the store.',image:'/quick-commerce-hero.png',cta:'Find what I need',prompt:'Show me electronics, personal care and household essentials available in this store',tone:'blue',alt:'Illustrative assortment of electronics, beauty, home, stationery, toys and groceries'},
 {tag:'ELECTRONICS & ACCESSORIES',title:'Stay connected.\nKeep your day moving.',body:'Find earphones, charging accessories and useful everyday tech. Compare the available options with your copilot.',image:'BOAT-ELEC-004',cta:'Explore everyday tech',prompt:'Show me earphones and charging accessories available in this store',tone:'lilac',alt:'boAt wired earphones'},
 {tag:'BEAUTY & PERSONAL CARE',title:'A little care.\nEvery single day.',body:'Skincare, bath and grooming essentials. Find the right pack and price before adding to your cart.',image:'NIVE-PCAR-022',cta:'Find personal care',prompt:'Show me skincare and personal care essentials',tone:'peach',alt:'Nivea moisturising cream'},
 {tag:'HOME & EVERYDAY ESSENTIALS',title:'Make room for\na better everyday.',body:'Restock cleaning supplies, household favourites and kitchen essentials alongside your groceries.',image:'LIZO-HHLD-011',cta:'Restock my home',prompt:'Show me household cleaning and kitchen essentials',tone:'mint',alt:'Lizol household floor cleaner'},
 {tag:'GROCERIES, SNACKS & DRINKS',title:'The essentials.\nAnd a little extra.',body:'Breakfast, pantry staples, snacks and drinks. Build a selection around your plans and budget.',image:'BRIT-BAKE-001',cta:'Plan my essentials',prompt:'Help me choose snacks, drinks and breakfast essentials',tone:'peach',alt:'Packaged breakfast essentials'},
];
export function ShoppingShowcase({onSelect,merchant=false}:{onSelect:(text:string)=>void;merchant?:boolean}){
 const [index,setIndex]=useState(0),[paused,setPaused]=useState(false),[hover,setHover]=useState(false),[visible,setVisible]=useState(false),[allowed,setAllowed]=useState(false);const [campaign,setCampaign]=useState<{title:string;body:string}|null>(null);const root=useRef<HTMLElement>(null);
 useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)');const sync=()=>setAllowed(!media.matches&&document.documentElement.dataset.motion!=='paused'&&!document.hidden);const load=()=>{try{const v=JSON.parse(localStorage.getItem('razorsharp-storefront-campaign-v1')||'null');setCampaign(v&&typeof v.title==='string'&&typeof v.body==='string'?v:null)}catch{setCampaign(null)}};sync();load();const observer=new IntersectionObserver(([e])=>setVisible(e.isIntersecting),{threshold:.25});if(root.current)observer.observe(root.current);media.addEventListener('change',sync);window.addEventListener('razorsharp:motion',sync);document.addEventListener('visibilitychange',sync);window.addEventListener('storage',load);window.addEventListener('campaign:updated',load);return()=>{observer.disconnect();media.removeEventListener('change',sync);window.removeEventListener('razorsharp:motion',sync);document.removeEventListener('visibilitychange',sync);window.removeEventListener('storage',load);window.removeEventListener('campaign:updated',load)}},[]);
 const items=campaign?[...slides,{tag:'GREEN BASKET · MERCHANT PROMOTION',title:campaign.title,body:campaign.body,image:'BRIT-BAKE-001',alt:'Merchant campaign product',cta:'Explore this campaign',prompt:'Show me breakfast products from the Green Basket campaign',tone:'peach'}]:slides;
 useEffect(()=>{if(paused||hover||!visible||!allowed)return;const timer=setInterval(()=>setIndex(i=>(i+1)%items.length),6500);return()=>clearInterval(timer)},[paused,hover,visible,allowed,items.length]);
 useEffect(()=>{const frame=requestAnimationFrame(()=>{if(campaign&&window.location.hash==='#campaign'){setIndex(slides.length);setPaused(true)}});return()=>cancelAnimationFrame(frame)},[campaign]);
 const current=items[index%items.length];const move=(i:number)=>{setPaused(true);setIndex((i+items.length)%items.length)};
 return <section ref={root} className={`shopping-showcase ${merchant?'showcase-merchant':''}`} aria-label="Shopping experience and campaign showcase" aria-roledescription="carousel" ><div onMouseEnter={()=>setHover(true)} onMouseLeave={()=>setHover(false)} onFocusCapture={()=>setPaused(true)} className={`showcase-frame showcase-${current.tone}`}>{campaign&&index%items.length===slides.length?<CampaignArtwork title={campaign.title} body={campaign.body} onSelect={()=>onSelect(merchant?'Show the storefront preview for '+campaign.title:'Build a breakfast from the Green Basket campaign: '+campaign.title)}/>:<div className="showcase-slide" key={index%items.length}><div className="showcase-copy"><span>{current.tag}</span><h2>{current.title}</h2><p>{current.body}</p><button onClick={()=>onSelect(merchant?'Show the storefront preview for '+current.title.replace('\n',' '):current.prompt)}>{merchant?'Explore placement preview':current.cta}<ArrowRight size={16}/></button></div><div className={`showcase-product-stage ${current.image.startsWith('/')?'showcase-category-scene':''}`}><span className="showcase-product-index">0{index%items.length+1}</span><Image src={current.image.startsWith('/')?current.image:`/products/${current.image}.webp`} alt={current.alt} unoptimized width={640} height={640}/><span className="showcase-product-caption">YOUR EVERYDAY, ALL TOGETHER</span></div></div>}</div><div className="showcase-controls"><span>{String(index%items.length+1).padStart(2,'0')} / {String(items.length).padStart(2,'0')}</span><span className="showcase-footnote">{index%items.length===0?'Guided by your intent. Approved by you.':'Campaign concept · prices and availability require confirmation'}</span><button aria-label="Previous campaign slide" onClick={()=>move(index-1)}><ArrowLeft size={15}/></button><button aria-label={paused?'Play campaign slides':'Pause campaign slides'} onClick={()=>setPaused(p=>!p)}>{paused?<Play size={13}/>:<Pause size={13}/>}</button><button aria-label="Next campaign slide" onClick={()=>move(index+1)}><ArrowRight size={15}/></button></div></section>
}
