"""Schema, tenant isolation and database roles for the commerce platform."""

from .engine import database_url, get_engine, get_sessionmaker, session_scope
from .roles import ALL_ROLES, APPEND_ONLY_TABLES, FINANCIAL_TABLES
from .schema import (
    RLS_TABLES,
    Approval,
    AuditEvent,
    Base,
    CheckoutVersion,
    DelegatedAuthority,
    ExecutionGrant,
    IdempotencyRecord,
    Merchant,
    OperatingMode,
    OutboxEvent,
    PaymentAttempt,
    PolicyAtSaleReceipt,
    Reservation,
    Tenant,
)
from .tenancy import (
    TENANT_SETTING,
    TenantContextError,
    current_tenant,
    require_tenant,
    set_tenant,
    tenant_scope,
)

__all__ = [
    "ALL_ROLES",
    "APPEND_ONLY_TABLES",
    "FINANCIAL_TABLES",
    "RLS_TABLES",
    "TENANT_SETTING",
    "Approval",
    "AuditEvent",
    "Base",
    "CheckoutVersion",
    "DelegatedAuthority",
    "ExecutionGrant",
    "IdempotencyRecord",
    "Merchant",
    "OperatingMode",
    "OutboxEvent",
    "PaymentAttempt",
    "PolicyAtSaleReceipt",
    "Reservation",
    "Tenant",
    "TenantContextError",
    "current_tenant",
    "database_url",
    "get_engine",
    "get_sessionmaker",
    "require_tenant",
    "session_scope",
    "set_tenant",
    "tenant_scope",
]
