"""Schema, tenant isolation and database roles for the commerce platform."""

from .engine import database_url, get_engine, get_sessionmaker, session_scope
from .roles import (
    ALL_ROLES,
    APP,
    APPEND_ONLY_TABLES,
    FINANCIAL_TABLES,
    KERNEL,
    WORKER,
    WRITE_GRANTS,
)
from .scenario_faults import ClaimedFault, claim_scenario_fault
from .schema import (
    RLS_TABLES,
    Approval,
    AuditEvent,
    Base,
    CheckoutVersion,
    DelegatedAuthority,
    ExecutionGrant,
    IdempotencyRecord,
    Merchant,
    OperatingMode,
    OutboxEvent,
    PaymentAttempt,
    PolicyAtSaleReceipt,
    Refund,
    Reservation,
    Tenant,
)
from .schema_service import (
    SERVICE_RLS_TABLES,
    SERVICE_TABLES,
    ApiSession,
    Cart,
    Checkout,
    Order,
    ProviderRequest,
    ReconciliationRun,
    ScenarioFault,
    ScenarioRun,
    WebhookInboxRow,
)
from .tenancy import (
    TENANT_SETTING,
    TenantContextError,
    current_tenant,
    require_tenant,
    set_tenant,
    tenant_scope,
)

__all__ = [
    "ALL_ROLES",
    "APP",
    "APPEND_ONLY_TABLES",
    "FINANCIAL_TABLES",
    "KERNEL",
    "RLS_TABLES",
    "SERVICE_RLS_TABLES",
    "SERVICE_TABLES",
    "TENANT_SETTING",
    "WORKER",
    "WRITE_GRANTS",
    "ApiSession",
    "Approval",
    "AuditEvent",
    "Base",
    "Cart",
    "Checkout",
    "CheckoutVersion",
    "ClaimedFault",
    "DelegatedAuthority",
    "ExecutionGrant",
    "IdempotencyRecord",
    "Merchant",
    "OperatingMode",
    "Order",
    "OutboxEvent",
    "PaymentAttempt",
    "PolicyAtSaleReceipt",
    "ProviderRequest",
    "ReconciliationRun",
    "Refund",
    "Reservation",
    "ScenarioFault",
    "ScenarioRun",
    "Tenant",
    "TenantContextError",
    "WebhookInboxRow",
    "claim_scenario_fault",
    "current_tenant",
    "database_url",
    "get_engine",
    "get_sessionmaker",
    "require_tenant",
    "session_scope",
    "set_tenant",
    "tenant_scope",
]
