"""The voice WebSocket contract (19.5, 19.12, 24.2): frames, tickets, Origin policy."""

from .frames import (
    AgentReply,
    AudioContract,
    BargeIn,
    ClientFrame,
    Degradation,
    DegradationKind,
    ErrorFrame,
    Interrupted,
    Ping,
    PlaybackEnded,
    ServerFrame,
    SessionReady,
    SpeechChunkHeader,
    SpeechEnd,
    SpeechStart,
    TextInput,
    TranscriptFinal,
    TranscriptPartial,
    dump_server_frame,
    parse_client_frame,
)
from .origin import OriginPolicy, OriginVerdict
from .tickets import IssuedTicket, TicketClaims, TicketError, TicketIssuer

__all__ = [
    "AgentReply",
    "AudioContract",
    "BargeIn",
    "ClientFrame",
    "Degradation",
    "DegradationKind",
    "ErrorFrame",
    "Interrupted",
    "IssuedTicket",
    "OriginPolicy",
    "OriginVerdict",
    "Ping",
    "PlaybackEnded",
    "ServerFrame",
    "SessionReady",
    "SpeechChunkHeader",
    "SpeechEnd",
    "SpeechStart",
    "TextInput",
    "TicketClaims",
    "TicketError",
    "TicketIssuer",
    "TranscriptFinal",
    "TranscriptPartial",
    "dump_server_frame",
    "parse_client_frame",
]
