"""The application factory.

``create_app`` assembles the whole service: settings, the merchant registry, the error
and idempotency handlers, and every router in
:data:`commerce_api.routers.ROUTERS`.

Two properties are worth stating because they are easy to lose:

**Import-safe.** Importing this module opens no connection, reads no environment variable
and starts no background task. ``create_app()`` with no argument reads the environment;
``create_app(settings)`` takes a configuration built from a dictionary. A test therefore
builds a fully working app without a ``.env`` anywhere near it, and an import in a
documentation tool cannot accidentally connect to a database.

**No unit edits this file.** Routers are included from a list that lives in
``routers/__init__.py``. That is what lets the catalogue, checkout, payment, evidence and
scenario units be built in parallel: each adds endpoints to its own module, and none of
them touches the application factory.

**Observability wraps everything and decides nothing.** The one middleware this service
installs binds a correlation scope, counts the request and times it; where it sits in the
stack, and why, is written out at :func:`create_app`.
"""

from __future__ import annotations

from collections.abc import AsyncIterator
from contextlib import asynccontextmanager
from typing import Final

from fastapi import FastAPI

from .errors import install_error_handlers
from .idempotency import install_idempotency_handler
from .merchants import MerchantRegistry
from .observability import ObservabilityMiddleware, configure_process_logging
from .routers import ROUTERS
from .settings import Settings, get_settings

__all__ = ["API_VERSION", "create_app"]

API_VERSION: Final[str] = "0.1.0"

_DESCRIPTION: Final[str] = """
Governed agentic commerce over the Transaction Assurance Kernel.

**Agents propose; deterministic systems authorize and execute.** Two consequences show up
directly in this contract:

* A refused money action is **HTTP 200 carrying a structured decision**, not a 4xx. The
  decision names a closed `RecoveryCode`, the exact deltas that caused it and the next
  version to approve. A denial is the system working (ADR 0003 D15).
* Errors -- as distinct from decisions -- are RFC 9457 problem details
  (`application/problem+json`).

Every mutation requires an `Idempotency-Key`. Re-sending one replays the original
response with `Idempotent-Replayed: true`; re-using one with a different body is refused
with 422 and executes nothing.

Amounts are integer minor units beside an ISO 4217 code. Timestamps are RFC 3339 UTC.
""".strip()


@asynccontextmanager
async def _lifespan(app: FastAPI) -> AsyncIterator[None]:  # noqa: ARG001 - ASGI contract
    """Process-level setup, run once when a server starts serving this app.

    Logging configuration belongs here rather than at import: a module that reconfigures
    logging when it is imported reconfigures it for anything that imports it, including a
    documentation tool and a test suite that had its own opinion. :func:`configure_process_logging`
    declines when something else already owns the root logger, so building an app inside
    pytest leaves pytest's capture alone.
    """
    configure_process_logging()
    yield


def create_app(settings: Settings | None = None) -> FastAPI:
    """Build the API.

    :param settings: an explicit configuration. Omit it to read the process environment
        through :func:`commerce_api.settings.get_settings`, which is what the server
        entry point does.

    The merchant registry is created per app rather than per process, so two apps in one
    test session hold separate simulated catalogues and one test's price injection cannot
    leak into another's assertions. In production there is one app and one process
    (ADR 0003 D14).
    """
    resolved = settings if settings is not None else get_settings()

    app = FastAPI(
        title="Governed Agentic Commerce",
        version=API_VERSION,
        description=_DESCRIPTION,
        # OpenAPI 3.1, so the schema speaks JSON Schema 2020-12 and nullable unions
        # generated by pydantic v2 survive into a generated client unchanged
        # (specification 24.1).
        openapi_version="3.1.0",
        docs_url="/docs",
        redoc_url=None,
        openapi_url="/openapi.json",
        lifespan=_lifespan,
    )

    app.state.settings = resolved
    app.state.merchants = MerchantRegistry()

    # Observability is the outermost thing this file installs, and it is a different
    # layer from the two calls below rather than a competitor for the same slot. Starlette
    # builds ServerErrorMiddleware -> user middleware -> ExceptionMiddleware -> router, and
    # the handlers installed below are registrations *inside* those two framework
    # middlewares, not entries in the user stack. So this sits above every handled refusal
    # and below the last-resort 500 handler, which is the right place for both of its jobs:
    # the scope is bound before any router code runs, so every log line inside the request
    # carries the correlation id; and the response it measures is the one the client
    # actually receives, RFC 9457 problem details and kernel denials included. Putting it
    # under ExceptionMiddleware instead would mean timing only the requests that did not
    # refuse anything, which is the half of the traffic nobody needs to see.
    app.add_middleware(ObservabilityMiddleware)

    # Handlers before routers: an exception raised while including a router should still
    # be a problem detail if it somehow reaches a client.
    install_error_handlers(app)
    install_idempotency_handler(app)

    for router in ROUTERS:
        app.include_router(router)

    return app
