"""Generate frontend frame types from the server contract. Run with --check in tests."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, get_args

from pydantic import TypeAdapter
from voice_runtime.wire.frames import ClientFrame, DegradationKind, ServerFrame

TARGET = Path(__file__).resolve().parents[1] / "apps/razorsharp-concept/lib/voice/wire.ts"


def ts_type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return str(schema["$ref"]).split("/")[-1]
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    for key in ("anyOf", "oneOf"):
        if key in schema:
            return " | ".join(ts_type(part) for part in schema[key])
    kind = schema.get("type")
    if kind == "array":
        return f"Array<{ts_type(schema.get('items', {}))}>"
    if kind == "object":
        if "properties" in schema:
            # Frames serialize their defaults too. Every outbound property is present.
            fields = [
                f"{json.dumps(name)}: {ts_type(value)};"
                for name, value in schema["properties"].items()
            ]
            return "{\n  " + "\n  ".join(fields) + "\n}"
        additional = schema.get("additionalProperties", {})
        return (
            "Record<string, "
            + (ts_type(additional) if isinstance(additional, dict) else "unknown")
            + ">"
        )
    return {
        "string": "string",
        "integer": "number",
        "number": "number",
        "boolean": "boolean",
        "null": "null",
    }.get(str(kind), "unknown")


def render() -> str:
    server = TypeAdapter(ServerFrame).json_schema()
    client = TypeAdapter(ClientFrame).json_schema()
    definitions = {**server.get("$defs", {}), **client.get("$defs", {})}
    lines = [
        "// Generated by scripts/generate_voice_wire.py. Do not edit by hand.",
        "export const VOICE_PROTOCOL_VERSION = 2 as const;",
        "export const DEGRADATION_KINDS = "
        + json.dumps(list(get_args(DegradationKind)))
        + " as const;",
    ]
    for name, schema in sorted(definitions.items()):
        lines.append(f"export type {name} = {ts_type(schema)};")
    lines += [
        f"export type ServerFrame = {ts_type(server)};",
        f"export type ClientFrame = {ts_type(client)};",
    ]
    return "\n\n".join(lines) + "\n"


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    result = render()
    if args.check:
        if not TARGET.exists() or TARGET.read_text() != result:
            raise SystemExit("Voice wire types are stale. Run scripts/generate_voice_wire.py.")
    else:
        TARGET.write_text(result)
