"""Payment provider adapters.

Every adapter in this package obeys the same three rules:

1. **The transport is injected.** Nothing here opens a socket. A caller supplies an
   ``HttpTransport``; tests supply a fake, and continuous integration never touches the
   provider or a credential. The production transport lives in ``action_executor`` (ADR
   0003 D3), and only the worker talks to Razorpay.
2. **Provider constraints are enforced here, not in the platform core** (specification
   12.5). The kernel does not need to know that Razorpay caps a receipt at 40 characters.
3. **An outcome that is not certain is reported as unknown.** Adapters return
   ``RecoveryCode`` values from ``commerce_domain.recovery``; they never invent a code
   and never soften ``PAYMENT_UNKNOWN`` into ``PAYMENT_FAILED``.

The Razorpay adapter's public surface is re-exported here so that the worker and the API
settings can write ``payment_adapters.create_order`` or
``payment_adapters.load_config_from_env`` without naming the provider module. The
provider-specific module remains importable as :mod:`payment_adapters.razorpay` for code
that wants to be explicit.
"""

from . import razorpay
from .razorpay import (
    API_BASE_URL,
    API_CREDENTIAL_VARIABLE,
    DEFAULT_TIMEOUT_SECONDS,
    EVENT_ID_HEADER,
    EVIDENCE_SOURCE,
    IDEMPOTENCY_HEADER,
    KEY_ID_VARIABLE,
    LIVE_KEY_PREFIX,
    MAX_RECEIPT_LENGTH,
    PRODUCTION_APPROVAL_VARIABLE,
    PROFILE_VARIABLE,
    REQUIRED_VARIABLES,
    SIGNATURE_HEADER,
    TEST_KEY_PREFIX,
    WEBHOOK_CREDENTIAL_VARIABLE,
    CaptureEvidence,
    CaptureLedger,
    ConfigurationError,
    CreateOrderResult,
    EvidenceMismatchError,
    FetchClassification,
    HttpRequest,
    HttpResponse,
    HttpTransport,
    InboxRecord,
    InboxStore,
    InMemoryInboxStore,
    OrderLookupResult,
    OrderPaymentsResult,
    PaymentFetchResult,
    ProviderEvidence,
    RazorpayAdapterError,
    RazorpayConfig,
    RazorpayProfile,
    RazorpayWebhookEvent,
    RefundDecision,
    RefundNotPermittedError,
    RefundPlan,
    RefundRefusal,
    RefundResult,
    RefundSpeed,
    RequestConstructionError,
    SignatureMismatchError,
    TransportError,
    TransportTimeoutError,
    UnmappableEventError,
    WebhookAdmission,
    WebhookInbox,
    apply_event,
    build_create_order_request,
    build_fetch_payment_request,
    build_order_lookup_request,
    build_order_payments_request,
    build_refund_request,
    classify_failure,
    create_order,
    dedup_key_for,
    execute_refund,
    fetch_order_payments,
    fetch_payment,
    find_order_by_receipt,
    header_value,
    load_config_from_env,
    may_fulfil,
    may_retry_after,
    must_reconcile_before_retry,
    parse_event,
    parse_json_body,
    parse_json_body_bytes,
    payment_signature_payload,
    payment_state_for_event,
    plan_refund,
    refund_idempotency_key,
    require_payment_signature,
    require_webhook_signature,
    requires_release_not_capture,
    verify_payment_signature,
    verify_webhook_signature,
)

__all__ = [
    "API_BASE_URL",
    "API_CREDENTIAL_VARIABLE",
    "DEFAULT_TIMEOUT_SECONDS",
    "EVENT_ID_HEADER",
    "EVIDENCE_SOURCE",
    "IDEMPOTENCY_HEADER",
    "KEY_ID_VARIABLE",
    "LIVE_KEY_PREFIX",
    "MAX_RECEIPT_LENGTH",
    "PRODUCTION_APPROVAL_VARIABLE",
    "PROFILE_VARIABLE",
    "REQUIRED_VARIABLES",
    "SIGNATURE_HEADER",
    "TEST_KEY_PREFIX",
    "WEBHOOK_CREDENTIAL_VARIABLE",
    "CaptureEvidence",
    "CaptureLedger",
    "ConfigurationError",
    "CreateOrderResult",
    "EvidenceMismatchError",
    "FetchClassification",
    "HttpRequest",
    "HttpResponse",
    "HttpTransport",
    "InMemoryInboxStore",
    "InboxRecord",
    "InboxStore",
    "OrderLookupResult",
    "OrderPaymentsResult",
    "PaymentFetchResult",
    "ProviderEvidence",
    "RazorpayAdapterError",
    "RazorpayConfig",
    "RazorpayProfile",
    "RazorpayWebhookEvent",
    "RefundDecision",
    "RefundNotPermittedError",
    "RefundPlan",
    "RefundRefusal",
    "RefundResult",
    "RefundSpeed",
    "RequestConstructionError",
    "SignatureMismatchError",
    "TransportError",
    "TransportTimeoutError",
    "UnmappableEventError",
    "WebhookAdmission",
    "WebhookInbox",
    "apply_event",
    "build_create_order_request",
    "build_fetch_payment_request",
    "build_order_lookup_request",
    "build_order_payments_request",
    "build_refund_request",
    "classify_failure",
    "create_order",
    "dedup_key_for",
    "execute_refund",
    "fetch_order_payments",
    "fetch_payment",
    "find_order_by_receipt",
    "header_value",
    "load_config_from_env",
    "may_fulfil",
    "may_retry_after",
    "must_reconcile_before_retry",
    "parse_event",
    "parse_json_body",
    "parse_json_body_bytes",
    "payment_signature_payload",
    "payment_state_for_event",
    "plan_refund",
    "razorpay",
    "refund_idempotency_key",
    "require_payment_signature",
    "require_webhook_signature",
    "requires_release_not_capture",
    "verify_payment_signature",
    "verify_webhook_signature",
]
