"""Runtime-agnostic core of the agent layer.

Nothing here imports ``google.adk`` or ``google.genai``; a source test enforces it. The
three concerns are the ones that must hold before any model is involved: third-party
text is fenced (:mod:`fencing`), a turn starts from the read its shape demands
(:mod:`grounding_rules`), and a write may name only what a tool returned this session
(:mod:`provenance`).
"""

from .fencing import (
    MAX_FENCED_CHARS,
    MAX_MERCHANT_TEXT_CHARS,
    MERCHANT_DATA_FENCE,
    OPERATOR_DATA_FENCE,
    SUGGESTION_CHIP_MAX_CHARS,
    WITHHELD,
    Fence,
    FencedText,
    sanitize_label,
    sanitize_suggestion_chips,
    scan,
    truncate_display,
)
from .grounding_rules import (
    CHECKOUT_RULES,
    DEFAULT_LEXICON,
    GROWTH_RULES,
    SHOPPING_RULES,
    SUPPORT_RULES,
    GroundingLexicon,
    GroundingRule,
    GroundingState,
    RuleInput,
    find_token,
    first_rule,
    forced_tool,
    matches_any,
    matches_terms_and_cues,
    rules_for,
)
from .provenance import (
    MAX_BASKET_LINES,
    MAX_LINE_QUANTITY,
    PROVENANCE_CAP,
    PROVENANCE_STATE_KEY,
    Held,
    SeenCheckout,
    SeenSku,
    SessionProvenance,
    check_case_provenance,
    check_checkout_provenance,
    check_line_count,
    check_order_provenance,
    check_proposal_provenance,
    check_quantity,
    check_sku_provenance,
    session_write_lock,
)

__all__ = [
    "CHECKOUT_RULES",
    "DEFAULT_LEXICON",
    "GROWTH_RULES",
    "MAX_BASKET_LINES",
    "MAX_FENCED_CHARS",
    "MAX_LINE_QUANTITY",
    "MAX_MERCHANT_TEXT_CHARS",
    "MERCHANT_DATA_FENCE",
    "OPERATOR_DATA_FENCE",
    "PROVENANCE_CAP",
    "PROVENANCE_STATE_KEY",
    "SHOPPING_RULES",
    "SUGGESTION_CHIP_MAX_CHARS",
    "SUPPORT_RULES",
    "WITHHELD",
    "Fence",
    "FencedText",
    "GroundingLexicon",
    "GroundingRule",
    "GroundingState",
    "Held",
    "RuleInput",
    "SeenCheckout",
    "SeenSku",
    "SessionProvenance",
    "check_case_provenance",
    "check_checkout_provenance",
    "check_line_count",
    "check_order_provenance",
    "check_proposal_provenance",
    "check_quantity",
    "check_sku_provenance",
    "find_token",
    "first_rule",
    "forced_tool",
    "matches_any",
    "matches_terms_and_cues",
    "rules_for",
    "sanitize_label",
    "sanitize_suggestion_chips",
    "scan",
    "session_write_lock",
    "truncate_display",
]
